Feat/add new provider
tokens-studio/figma-plugin pull request #1392
Opened 2022-10-28 12:33 UTC by andrewx82

2022-10-28 12:34 UTC, andrewx82 commented
This is an update of the old draft copy of the PR I had open https://github.com/six7/figma-tokens/pull/1140

.I've resolved the issues with the event like interface as well as the added tests and checked the e2e flow

2022-10-28 13:11 UTC, andrewx82 commented
@LiamMartens apologies for the long delay

2022-11-01 18:41 UTC, six7 commented
> The failure of the test coverage seems to be at a pipeline level I believe ? 

Yes, we currently have a problem with external contributions and the test coverage.

I'll review over the coming days, i don't know when @LiamMartens has capacity though

2022-11-02 04:03 UTC, LiamMartens commented
@six7 I have started reviewing this and will finish tomorrow!

2022-11-03 00:39 UTC, LiamMartens requested changes
Some general code feedback;

Furthermore also a question to @six7, it might be worth performing a migration for this. Ie upon reading the `ApiProvidersProperty`. This way we can consolidate the providers:
- Move the JSONBin and URL types to this GenericVersioned type with the appropriate settings
- Remove JSONBin and URL from our codebase in favor of this generic impl.

2022-11-03 00:39 UTC, LiamMartens commented on src/storage/GenericVersionedStorage.ts
> +      case GenericVersionedStorageFlow.READ_ONLY:
We should probably just throw an error if we are trying to create in read only mode

2022-11-03 00:39 UTC, LiamMartens commented on src/storage/GenericVersionedStorage.ts
> +    const dataObject: GenericVersionedData = {
Same thing here, it might make sense to throw an error if this is set-up as read only and we try to write

2022-11-03 07:50 UTC, six7 commented on src/app/components/StorageItemForm/GenericVersioned.tsx
> +          <div className="bg-red-200 text-red-700 rounded p-4 text-xs font-bold" data-cy="provider-modal-error">
We don't so far, it's one of the remaining things to do in https://github.com/six7/figma-tokens/issues/1246 - for this PR I'd say this usage is OK as we'll replace it everywhere those error boxes are used

2022-11-03 07:52 UTC, six7 commented
> Some general code feedback;
> 
> Furthermore also a question to @six7, it might be worth performing a migration for this. Ie upon reading the `ApiProvidersProperty`. This way we can consolidate the providers:
> 
> * Move the JSONBin and URL types to this GenericVersioned type with the appropriate settings
> * Remove JSONBin and URL from our codebase in favor of this generic impl.

I'm wondering how we could perform a migration if items are stored on user's devices? I.e. a user could open the plugin 5 months from now. Is there a good way how we could create these migrations to be run on `next open` - even if that isn't now but rather later?

2022-11-06 21:21 UTC, LiamMartens commented
@six7 my suggestion would be to create some kind of migration system (potentially based on last plugin version) in the outgoing function of the `ApiProvidersProperty` for example 

Currently this looks like this:
```
export const ApiProvidersProperty = new FigmaStorageProperty<StorageTypeCredentials[]>(
  FigmaStorageType.CLIENT_STORAGE,
  'apiProviders',
  (incoming) => JSON.stringify(incoming),
  (outgoing) => {
    type PossibleIncomingType = StorageTypeCredentials[] | Record<string, StorageTypeCredentials>;
    const result = tryParseJson<PossibleIncomingType>(outgoing) ?? [];
    if (Array.isArray(result)) return result;
    return Object.values(result).filter((value) => (
      typeof value === 'object'
    ));
  },
);
```

But we could add migrations here so it can update the JSONBin and URL providers to be the generic one instead upon reading (and potentially immediately write it back as well)

2022-11-07 06:43 UTC, andrewx82 commented on src/app/components/StorageItemForm/GenericVersioned.tsx
> +                className="p-4 hover:bg-gray-100 rounded focus:outline-none"
Sure thing, I think at the time I did the initial PR that was still the de facto way.

2022-11-07 06:51 UTC, andrewx82 commented on src/app/components/StorageItemForm/GenericVersioned.tsx
> +    const index = Number(e.target.getAttribute('data-index'));
I think you're referring to this line correct?

 ` const newHeaders = removedHeaders.filter((x) => x.name.length);`
 
 that works in tandem with the header initialization where I add in an extra item with an empty name and value .
 
I did that so it would fit with the current system of always having a row at the for a user to fill out, but also so that it prevents a user from potentially having multiple empty header rows they would need to close.

Also so that we wouldn't need to do another cleanup pass later on before the provider was created to filter out any potentially empty rows as well

2022-11-07 06:59 UTC, andrewx82 commented on src/app/components/StorageItemForm.tsx
> +    values = getInitialValues(values);
I agree, I hate this, it moves the flow outside the actual form handlers themselves

2022-11-07 07:20 UTC, andrewx82 commented on src/storage/GenericVersionedStorage.ts
> +      case GenericVersionedStorageFlow.READ_ONLY:
No that would be a valid case. The "creation" would check against the remote to pull the latest tokens at the time of setup.

2022-11-07 13:40 UTC, andrewx82 commented on src/app/components/StorageItemForm/GenericVersioned.tsx
> +    if (validationResult.success) {
I used the same code as the other forms are using when it comes to validation, but you're right, I didn't see them display the errors to the user by using the validationResult

2022-11-08 17:46 UTC, andrewx82 commented
@LiamMartens Do you think the new changes are satisfactory?

2022-11-08 20:45 UTC, six7 commented
> @six7 my suggestion would be to create some kind of migration system (potentially based on last plugin version) in the outgoing function of the `ApiProvidersProperty` for example
> 
> Currently this looks like this:
> 
> ```
> export const ApiProvidersProperty = new FigmaStorageProperty<StorageTypeCredentials[]>(
>   FigmaStorageType.CLIENT_STORAGE,
>   'apiProviders',
>   (incoming) => JSON.stringify(incoming),
>   (outgoing) => {
>     type PossibleIncomingType = StorageTypeCredentials[] | Record<string, StorageTypeCredentials>;
>     const result = tryParseJson<PossibleIncomingType>(outgoing) ?? [];
>     if (Array.isArray(result)) return result;
>     return Object.values(result).filter((value) => (
>       typeof value === 'object'
>     ));
>   },
> );
> ```
> 
> But we could add migrations here so it can update the JSONBin and URL providers to be the generic one instead upon reading (and potentially immediately write it back as well)

I like that! On road, migrate and change the stored data. We'd probably need to keep this in the plugin for a while - but eventually be able to remove it.

2022-11-15 12:16 UTC, andrewx82 commented
Hi all, are the updated changes satisfactory?

2022-11-19 10:10 UTC, six7 requested changes
Just some smaller items I noticed. I'll DM you in Slack for more!

2022-11-19 10:10 UTC, six7 commented on src/stories/GenericVersionedStorageForm.stories.mdx
> +      flow: GenericVersionedStorageFlow.READ_WRITEt,
is the t at the end on purpose?

2022-11-19 10:10 UTC, six7 commented on src/app/store/providers/generic/versionedStorage.ts
> +    if (!id) throw new Error('Missing Generic Versioned Storage ID ');
```suggestion
    if (!id) throw new Error('Missing Generic Versioned Storage ID');
```

2022-11-19 10:10 UTC, six7 commented on src/app/store/providers/generic/versionedStorage.ts
> +        // B) Overwrite Remote changes
We can remove that part from here (we never got to that part for JSONBin but something we should do in a future release - for all providers)

2022-11-19 10:10 UTC, six7 commented on src/app/components/StorageItemForm/GenericVersioned.tsx
> +          <div className="font-bold">Additional Headers</div>
Can we change this to a `<Heading>` so we're not using Tailwind here?

2022-11-21 09:25 UTC, andrewx82 commented on src/stories/GenericVersionedStorageForm.stories.mdx
> +      flow: GenericVersionedStorageFlow.READ_WRITEt,
Great catch

2022-11-24 16:06 UTC, andrewx82 commented
I've created a toy storage endpoint that uses the CREATE flow https://github.com/andrewx82/figma-tokens-generic-storage-example

2022-12-06 09:23 UTC, andrewx82 commented
I've altered the merge target to be the `next` branch to get access to the new updates to ensure there are no regressions, as well as added in the icons support.

2022-12-16 08:51 UTC, merged