1436 accept null value to un assign previously added value
tokens-studio/figma-plugin pull request #1478
Opened 2022-12-13 02:25 UTC by swordEdge

https://www.loom.com/share/1e9f6825db0140b6b61caaf3463935d8

2022-12-13 07:02 UTC, six7 requested changes
I'll test this in a bit, looks good! Only some minor comments

2022-12-13 19:33 UTC, six7 commented
Test coverage is failing as well, let's get that green, comments resolved and then 👍

2022-12-14 01:41 UTC, swordEdge commented on src/app/components/InspectorTokenSingle.tsx
> +import { IconBrokenLink, IconValueNone } from '@/icons';
> Can you use ValueNoneIcon instead from radix icons?

> Where can I get ValueNoneIcon? Is this already exist in the plugin?

2022-12-14 01:43 UTC, swordEdge commented on src/plugin/asyncMessageHandlers/remapTokens.ts
> +      oldName, newName, updateMode, category,
> Is this change required? What does it get us?

> Not required. Just wanted to remove same name value. There is another `tokens` value in this code.
Anyway revert this change.

2022-12-14 06:32 UTC, six7 commented on src/app/components/InspectorTokenSingle.tsx
> +import { IconBrokenLink, IconValueNone } from '@/icons';
```
import { ValueNoneIcon } from '@radix-ui/react-icons'
```

2022-12-14 13:26 UTC, swordEdge commented on src/plugin/asyncMessageHandlers/setNoneValuesOnNode.ts
> +          entries: [nodeToUpdate], values: newEntries, shouldRemove: true, tokensMap,
I think we're using cache here.

2022-12-14 19:41 UTC, six7 approved these changes

2022-12-15 20:41 UTC, six7 approved these changes

2022-12-15 20:41 UTC, merged