1166 introduce color modifiers
tokens-studio/figma-plugin pull request #1498
Opened 2022-12-28 14:01 UTC by swordEdge

2022-12-29 17:36 UTC, six7 reviewed
havent been able to fix the convertModifiedColorToHex error you mentioned either :/

2022-12-29 17:36 UTC, six7 commented on src/app/components/EditTokenForm.tsx
> +  const handleColorModifyChange = React.useCallback((newModify: ColorModifier) => {
should we move this logic also into ColorTokenForm? then it would be nicely separated?

2022-12-29 17:36 UTC, six7 commented on src/app/store/useManageTokens.tsx
> +  $extensions?: { 'com.figmatokens': { modify: ColorModifier } }
can we replace all occurences of `com.figmatokens` with `studio.tokens` ? We've changed our name recently, so let's reflect that as well in the extension 👍

2022-12-29 17:36 UTC, six7 commented on src/utils/alias/__tests__/getAliasValue.test.ts
> +      name: 'colors.ligth-extension',
`light` not `ligth`

2023-01-05 11:11 UTC, SorsOps commented
Took at look at the issue when having Figma execute the built bundle, seems to be colorjs.io has ES6 code present in all their dist files. Easiest thing is to just have a loader handle it 

The following changes need to be done to resolve it 

In babel.config.js

```js
...
  plugins: ['@babel/proposal-class-properties', '@babel/proposal-object-rest-spread', "@babel/transform-typescript","@babel/plugin-proposal-private-methods"],
  ...
```

In webpack.config.js (and webpack-transform.config.js to be safe) , add the following under rules

```js
      {
        test: /\.c?js$/,
        use: [
          {
            loader: 'babel-loader',
          },
        ],
        exclude:  /node_modules\/(?!(colorjs.io)\/)/,
      },
```

This means that we exclude transpilation of all other node module but the colorjs.io module. Technically it could be an include ,but it handles an raw js we use in the future

and lastly 

```sh
yarn add -D @babel/plugin-proposal-private-methods
```

Then our webpack should handle transpiling it down to ES5

2023-01-05 12:31 UTC, SorsOps commented on src/utils/convertModifiedColorToHex.ts
> +import Color from 'colorjs.io/dist/color.legacy';
The babel loader should fix our issues for us
```suggestion
import Color from 'colorjs.io';
```

2023-01-06 09:21 UTC, six7 requested changes
some more things i encountered:
- we're currently saving the `value` field as a `string` in JSON. can we save it as a `number` instead?
- can you add something to the tooltip of color tokens that use a modifier? just beneath the value: `lighten(0.5) / LCH` so `{operation}({value}) / {space})` or for mix: `mix(#ffffff, 0.5) / LCH`.

2023-01-06 09:21 UTC, six7 commented on src/app/components/ColorTokenForm.tsx
> +              tooltip="Add a new modify"
```suggestion
              tooltip="Add new modifier"
```

2023-01-06 21:40 UTC, six7 commented on src/app/components/ColorTokenForm.tsx
> +            className="block w-4 h-4 rounded-sm cursor-pointer shadow-border shadow-gray-300 focus:shadow-focus focus:shadow-primary-400"
could you convert this to Stitches css? we plan to remove tailwind.

2023-01-06 21:40 UTC, six7 commented on src/app/components/ColorTokenForm.tsx
> +                        className="block w-4 h-4 rounded-sm cursor-pointer shadow-border shadow-gray-300 focus:shadow-focus focus:shadow-primary-400"
could you convert this to Stitches css? we plan to remove tailwind.

2023-01-06 21:40 UTC, six7 commented on src/app/components/ColorTokenForm.tsx
> +      <div className="flex p-2 mt-2 font-mono text-gray-700 bg-gray-100 border-gray-300 rounded text-xxs itms-center">
could you convert this to Stitches css? we plan to remove tailwind.

2023-01-06 21:40 UTC, six7 commented on src/app/components/ColorTokenForm.tsx
> +          <div className="w-4 h-4 mr-1 border border-gray-200 rounded" style={{ background: String(displayColor) }} />
could you convert this to Stitches css? we plan to remove tailwind.

2023-01-08 09:15 UTC, six7 commented on src/utils/is/isSingleColorToken.ts
> +export function isSingleColorToken(token: SingleToken | any): token is SingleColorToken {
Let's call this isColorToken instead. Color tokens can only be single.

2023-01-08 09:17 UTC, six7 commented on src/app/components/ColorPickerTrigger.tsx
> +  return (
Never put an onClick on a div, this is bad for a11y. Instead, render a button: `styled('button', ..`

2023-01-09 20:42 UTC, six7 commented
@swordEdge One last thing: Can you make sure users can enter both `0.5` as well as `0,5` for the `value`? For me right now I have to enter `0,05` - I believe this depends on localization? Can we parse the input on change and change that to 0.5 always (the decimal point, not the decimal comma). Figma does the same if you type `0,5` in a width in Figma it converts to `0.5`.

2023-01-10 22:45 UTC, six7 commented
I found one more edge case:

If a user already had something else in their `$extensions` property (which will be likely given this is going to be how in the spec users are able to add extra metadata) we currently override the whole object

To reproduce:
- add a $extensions field with some other identifier to a token
- then add a color modifier to that token via the UI and save
- notice how we removed the other $extensions value.

I'd expect that same $extensions property to still be there. We do not want to delete that for the user, we just want to append.

https://user-images.githubusercontent.com/4548309/211678220-afe9d2a8-4ff2-4378-81c3-da0b8557e56f.mp4

2023-01-11 17:52 UTC, six7 approved these changes
🎉

2023-01-11 17:52 UTC, merged