display boxshadow input when changing the mode
tokens-studio/figma-plugin pull request #1580
Opened 2023-02-01 00:44 UTC by swordEdge

2023-02-06 18:51 UTC, six7 commented
Can we change it so when you detach the values of the aliased tokens get inserted? In that case `2 2 2 2 etc` ?

2023-02-11 12:44 UTC, six7 requested changes
Two things:

- When clicking the `+` initially, can we make it so that there's a second form added? Right now I have to press twice to add the second form
- There's a strange case where when going to reference mode and then back to input mode I can no longer press the +. see video below
- Would it be possible that we just allow users to also use multiple when using aliases? So we can do a shadow that consists of many aliases to other shadows? That way you could keep the + in alias mode, but it'd just give you multiple of these single-reference field inputs?

https://user-images.githubusercontent.com/4548309/218258590-999a37e9-9fe1-4345-bc26-75cf896dc90d.mp4

2023-02-15 03:23 UTC, swordEdge commented
> Two things:
> 
> * When clicking the `+` initially, can we make it so that there's a second form added? Right now I have to press twice to add the second form
> * There's a strange case where when going to reference mode and then back to input mode I can no longer press the +. see video below
> * Would it be possible that we just allow users to also use multiple when using aliases? So we can do a shadow that consists of many aliases to other shadows? That way you could keep the + in alias mode, but it'd just give you multiple of these single-reference field inputs?


> @six7 Implemented all features you mentioned except the third part (add button on alias mode). Do you think it is necessary? And If it is really neccessary, I'd like you to create a new issue about that one.

2023-02-15 08:17 UTC, six7 requested changes

2023-02-15 08:17 UTC, six7 commented on src/app/components/BoxShadowInput.tsx
> +                mappedItems.map((token, index) => (
instead of casting all values `as TokenBoxShadowValue` can you just specify a return type here?

2023-02-27 18:48 UTC, six7 approved these changes

2023-02-27 18:48 UTC, merged