Second screen
tokens-studio/figma-plugin pull request #1583
Opened 2023-02-01 11:02 UTC by roppazvan

2023-02-02 21:52 UTC, six7 requested changes
Nice!

2023-02-02 21:52 UTC, six7 commented on src/app/store/models/tokenState.tsx
> +    setUsedTokenSet: (state, data: UsedTokenSetsMap) => ({
Why was this changed?

2023-02-02 21:52 UTC, six7 commented on src/types/SecondScreen.ts
> +export type Token = SingleToken;
Why not use SingleToken in the first place?

2023-02-02 21:52 UTC, six7 commented on src/types/SecondScreen.ts
> +  ftData: {
Can we change this? We are no longer called Figma Tokens

2023-02-02 21:52 UTC, six7 commented on src/types/SecondScreen.ts
> +  owner_email?: string;
When do we use snake_case and when camelCase?

2023-02-02 21:52 UTC, six7 commented on src/types/Auth.ts
> +  repeatedPassword?: string;
Again feels weird to mix cases like that

2023-02-02 21:52 UTC, six7 commented on src/context/AuthContext.tsx
> +      handleLogin(data);
Can you add mixpanel track() events for all these?

2023-02-02 21:52 UTC, six7 commented on src/app/components/SecondScreen/index.tsx
> +        background: isEnabled ? 'rgba(65, 63, 63, 1)' : 'transparent',
Can you use a token here? We need to support both light and dark mode, we cannot use rgb values

2023-02-02 21:52 UTC, six7 commented on src/app/components/SecondScreen/index.tsx
> +        borderRadius: '6px',
```suggestion
        borderRadius: '$button',
```

2023-02-02 21:52 UTC, six7 commented on src/app/components/AuthModal/index.tsx
> +    (e: any) => {
Can we remove the any?

2023-02-02 21:52 UTC, six7 commented on src/app/components/AuthModal/index.tsx
> +        <Button variant="primary" onClick={onSubmitButtonClick}>
Can we still integrate a Forgot password link?

2023-02-03 08:00 UTC, roppazvan commented on src/app/store/models/tokenState.tsx
> +    setUsedTokenSet: (state, data: UsedTokenSetsMap) => ({
I needed a way to update the `usedTokenSet` field in the state with the data from second-screen. And there was no way to do that in a straightforward way. same for themes.

2023-02-03 08:21 UTC, roppazvan commented on src/types/SecondScreen.ts
> +  owner_email?: string;
snake case is the recommended way for posgtres . Camel case is for the actual data inside ftData, I'll rename these to be more consistent
![Screenshot 2023-02-03 at 10 17 11](https://user-images.githubusercontent.com/21245398/216548310-141e806d-23e2-4eff-b957-0d5d50010eb4.png)

2023-02-03 10:24 UTC, roppazvan commented on src/types/Auth.ts
> +  repeatedPassword?: string;
yeah, this is a mistake. theres no refresh_token there.

2023-02-06 18:49 UTC, merged