fix tokenset tree breaking
tokens-studio/figma-plugin pull request #1598
Opened 2023-02-08 01:42 UTC by swordEdge

2023-02-11 12:26 UTC, six7 requested changes
Can you also fix the performance of the tree? It feels really slow right now, every time an item moves it seems to stutter for a bit there.

You could also refactor the tree component itself, it still has some logic in it about the `TokenSetListOrTree` - we *always* use the Tree since a few versions ago, no need for the List anymore.

https://user-images.githubusercontent.com/4548309/218257833-5670c8d0-6212-42ef-bea8-f1ad43cbf515.mp4

2023-02-15 08:20 UTC, six7 requested changes

2023-02-15 08:20 UTC, six7 commented on src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx
>            <TokenSetListOrTree
The name of this component also no longer makes sense as all we have is a Tree, no `or tree`

2023-02-15 08:20 UTC, six7 commented on src/app/components/TokenSetListOrTree/TokenSetListOrTree.tsx
>  type SharedProps<T extends TreeOrListItem> = {
the name of this type as well

2023-02-15 08:20 UTC, six7 commented on src/app/components/TokenSetListOrTree/TokenSetListOrTree.tsx
>  type Props<T extends TreeOrListItem> = SharedProps<T>;
here too

2023-02-15 08:20 UTC, six7 commented on src/app/components/TokenSetListOrTree/TokenSetListOrTree.tsx
>  export function TokenSetListOrTree<T extends TreeOrListItem>({
here too

2023-02-16 09:09 UTC, swordEdge commented on src/app/components/TokenSetListOrTree/TokenSetListOrTree.tsx
>  export function TokenSetListOrTree<T extends TreeOrListItem>({
@six7 Could you merge this pr if functionality works. Test coverage is still failed but it requires me to test drag function. You know grab and drag.

2023-02-27 18:45 UTC, six7 approved these changes

2023-02-27 18:45 UTC, merged