1671 base font size token doesnt pick up tokens
tokens-studio/figma-plugin pull request #1672
Opened 2023-03-08 12:31 UTC by swordEdge

2023-03-11 11:47 UTC, six7 requested changes

2023-03-11 11:47 UTC, six7 commented on src/plugin/node.ts
> +    if (aliasBaseFontSize.startsWith('{')) {
shouldnt we already have the value of `aliasBaseFontSize` in settings? you query on line 197 of Tokens.tsx the aliasValue? That should be the real value to be used, right? No need to further query the alias value of it'd already be in store?

2023-03-13 00:34 UTC, swordEdge commented on src/plugin/node.ts
> +    if (aliasBaseFontSize.startsWith('{')) {
> shouldnt we already have the value of `aliasBaseFontSize` in settings? you query on line 197 of Tokens.tsx the aliasValue? That should be the real value to be used, right? No need to further query the alias value of it'd already be in store?

@six7 Yes. We store the real value to be used. But when we switch the theme, it causes the document update. But at this time, the real value has not been updated yet. It will be updated after this process. That's why I resolved the aliasValue here.

2023-03-14 06:49 UTC, six7 commented on src/plugin/node.ts
> +    if (aliasBaseFontSize.startsWith('{')) {
Then dont we have a function to getAliasVallue? I feel we shouldnt have alias resolve logic in node.ts - we should import a function that does it.

Or even better, make sure that by the time the document updates the base font size token has been updated

2023-03-14 17:12 UTC, six7 requested changes

2023-03-14 17:12 UTC, six7 commented on src/app/store/models/settings.tsx
> +      dispatch.tokenState.updateDocument({ shouldUpdateNodes: true });
can you set this to `shouldUpdateNodes: false`?

We wouldnt want a change in the base font size trigger a document wide update, which could mean the users would have to wait a long time. So instead lets just update the document, but not the nodes.

2023-03-19 09:45 UTC, merged