1062 support syntax highlighting in json editor
tokens-studio/figma-plugin pull request #1700
Opened 2023-03-18 01:33 UTC by swordEdge

2023-03-19 09:36 UTC, six7 requested changes

2023-03-19 09:36 UTC, six7 commented on src/AsyncMessageChannel.ts
> +      if (!msg?.id || !msg.message || !msg.message.type.startsWith('async/')) return;
shouldn't `msg` always be present?

2023-03-19 09:36 UTC, six7 commented on src/app/components/JSONEditor.tsx
> +/*
we can remove those comments

2023-03-19 09:36 UTC, six7 commented on src/app/components/JSONEditor.tsx
> -  const editProhibited = useSelector(editProhibitedSelector);
we will still need `editProhibited` for the case where users are in read-only mode

2023-03-19 09:36 UTC, six7 commented on src/app/components/JSONEditor.tsx
> +    if (value) handleChange(value);
is there a case where value is null? shouldnt the editor *always* have a value? even when its `""` ?

2023-03-19 09:36 UTC, six7 commented on src/app/components/JSONEditor.tsx
> +        theme="vs-dark"
```suggestion
        theme="vs-dark"
        options={{
          minimap: {
            enabled: false,
          },
          lineNumbers: 'off',
          wordWrap: 'on',
          contextmenu: false,
        }}
```

2023-03-21 03:25 UTC, swordEdge commented on src/app/components/JSONEditor.tsx
> +    if (value) handleChange(value);
The type of parameter of onChange function in Moncaco editor is string | undefined.

2023-03-21 06:48 UTC, six7 approved these changes
🙌

2023-03-21 06:48 UTC, merged