add document modifier
tokens-studio/figma-plugin pull request #1706
Opened 2023-03-21 07:54 UTC by swordEdge

https://user-images.githubusercontent.com/25951419/226546208-c0b25307-6542-4d1e-85e3-cec0cb37e256.mp4

2023-03-21 21:38 UTC, six7 requested changes

2023-03-21 21:38 UTC, six7 commented on src/plugin/node.ts
> +        acc[key] = modifier.type === ColorModifierTypes.MIX ? `mix(${modifier.color}, ${modifier.value}) / ${modifier.space}` : `${modifier.type}(${modifier.value}) / ${modifier.space}`;
According to the issue it should be `{color} / lighten(0.2) / lch` - right now it's missing the referenced color token.

2023-03-22 00:12 UTC, swordEdge commented on src/plugin/node.ts
> +        acc[key] = modifier.type === ColorModifierTypes.MIX ? `mix(${modifier.color}, ${modifier.value}) / ${modifier.space}` : `${modifier.type}(${modifier.value}) / ${modifier.space}`;
Updated it.
![image](https://user-images.githubusercontent.com/25951419/226769607-2822d5a7-fca1-4aa7-a887-891c8c9f0643.png)

2023-03-22 18:22 UTC, six7 approved these changes
👍

2023-03-22 18:22 UTC, merged