update the tokenSet order according to GUI
tokens-studio/figma-plugin pull request #1717
Opened 2023-03-22 18:20 UTC by swordEdge

2023-03-22 20:50 UTC, six7 requested changes

2023-03-22 20:50 UTC, six7 commented on src/app/components/TokenSetTree.tsx
> +  React.useEffect(() => {
Wouldn't a better place to fix this bug be where we create and rename token sets? So we make sure that it is already inserted into the right place when we create token sets? Instead of relying on the UI to do that as a side effect?

2023-03-23 00:35 UTC, swordEdge commented on src/app/components/TokenSetTree.tsx
> +  React.useEffect(() => {
@six7 We can fix this bug in the place where we create and rename token sets. But how about the users with old data like the user who mentioned this issue. He will get this error even though after fixing. Because tokenSets are ordered when we add or rename. What's your opinion? Still can we fix in the place where we create and rename token sets?

2023-03-24 07:50 UTC, six7 commented on src/app/components/TokenSetTree.tsx
> +  React.useEffect(() => {
I agree, this sounds like a good solution that also fixes older sets of users.

Can you still additionally add the logic to insert in the right place when creating and renaming? That way we do not have to rely on the UI to do the magic for us.

2023-03-24 21:11 UTC, six7 approved these changes

2023-03-24 21:11 UTC, merged