1609 show diff before pushing and pulling changes
tokens-studio/figma-plugin pull request #1784
Opened 2023-04-03 13:07 UTC by swordEdge

2023-04-10 09:39 UTC, six7 requested changes
Very cool!

I added some comments.

A slightly bigger request: Can we change the `Push` logic so that it's not separate into 2 steps? Instead, can we just add a `Commit` tab to the list of tabs? And then we have `Commit | Diff | JSON` as Tabs. That way we save users a click when they want to push changes, but they still will be able to see their changes? And if the `branch` was changed, we'd retrigger the comparison for the diff/json in the tabs?

2023-04-10 09:39 UTC, six7 commented on src/app/components/ChangedStateList.tsx
> +                        padding: '$2',
i think it could make it a bit cleaner to move this into a StyledText and then reuse that one with a `variant` prop of either `success` or `danger`

2023-04-10 09:39 UTC, six7 commented on src/app/components/ChangedTokenItem.tsx
> +              padding: '$2',
same here, theres lots of these success / danger text items that could be a reusable component instead

2023-04-10 09:39 UTC, six7 commented on src/app/components/ChangeStateListingHeading.tsx
> +      <StyledTokenGroupHeadingButton
i think it could be better not to reuse the token group heading here and instead have its own component? if we later decide we want to change the token group heading component this could have unexpected implications here

2023-04-10 09:39 UTC, six7 commented on src/app/components/PullDialog.tsx
> +              This will override your current tokens. Make sure you copy your changes if you want to preserve theme.
slight typo: should be `preserve them`

2023-04-10 09:39 UTC, six7 commented on src/app/components/PullDialog.tsx
> +              This will override your current tokens. Make sure you copy your changes if you want to preserve theme.
can we change this so it only changes the part that need to be changed for Loading ? right now it seems to be duplicate content.

Also, can we remove this sentence from the loading state? I know it was in the initial designs, but from testing it it feels like it's better if it doesn't show it during Loading

2023-04-10 09:39 UTC, six7 commented on src/app/components/PushJSON.tsx
> +            <pre style={{ padding: '$2 $4' }}>
one thing i noticed here in the JSON (either of them) is that when you have a very long description it currently will not wrap and will lead to horizontal scroll. we should make it so that text wraps

(to reproduce load the example Preset (Tools > Load preset) and then push this

![Image](https://user-images.githubusercontent.com/4548309/230874810-6304de40-e31b-48d1-aae7-498327706eb7.png)

2023-04-10 09:39 UTC, six7 commented on src/app/components/PushJSON.tsx
> +            <ChangeStateListingHeading onCollapse={handleSetIntCollapsed} tokenKey="$themes" label="$themes" isCollapsed={collapsedTokenSets.includes('$themes')} />
one thing that doesnt yet work is when i `Alt + Click` on an expanded token set i would expect that **all** token sets would collapse. much like when i do that on a collapsed on all expand

2023-04-10 09:39 UTC, six7 commented on src/app/store/remoteTokens.tsx
> +    pullDialog('loading');
should this be renamed to `showPullDialog` ? to match what we have for `closePullDialog`? that way it's more descriptive

2023-04-10 09:39 UTC, six7 commented on src/app/components/PullDialog.tsx
> +                Override Tokens
```suggestion
                Override tokens
```

2023-04-14 21:02 UTC, six7 requested changes
Nice! 1 minor thing:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/4548309/232154101-aaa62fb3-0f80-4ff7-9625-671801a8e0bb.png">

the horizontal scroll is still there in the JSON tab when there's a really long text string in the JSON

2023-04-17 20:14 UTC, swordEdge commented
> Nice! 1 minor thing:
> 
> <img alt="image" width="641" src="https://user-images.githubusercontent.com/4548309/232154101-aaa62fb3-0f80-4ff7-9625-671801a8e0bb.png">
> 
> the horizontal scroll is still there in the JSON tab when there's a really long text string in the JSON

> On my side, it was fixed already. Could you try again on your side? @six7 
![image](https://user-images.githubusercontent.com/25951419/232599753-5b0d9ad4-5f34-4b13-b264-6fc53eff5863.png)

2023-04-19 19:22 UTC, six7 approved these changes
🔥

2023-04-19 19:23 UTC, merged