add filter input
tokens-studio/figma-plugin pull request #1793
Opened 2023-04-07 07:45 UTC by swordEdge

2023-04-10 09:55 UTC, six7 commented
Not sure if this is ready for review yet, but:

- Can we change the logic so it only displays the search bar if there's more than 5 branches? Right now it displays even when there's just 1

There seems to be some padding issue on the right of the second dropdown that appears. Let's make this look like the first

<img width="387" alt="image" src="https://user-images.githubusercontent.com/4548309/230879311-c864d391-6345-4ce2-b098-d9201a56c8a0.png">

There seems to be another padding issue with the `branch` item compared to the `Create new branch from..`
<img width="224" alt="image" src="https://user-images.githubusercontent.com/4548309/230879380-04304fc8-4ac1-4645-a744-a979351411c7.png">
(notice the blue background doesnt span to the right)
<img width="207" alt="image" src="https://user-images.githubusercontent.com/4548309/230879415-878970bc-2d70-4722-8785-a65f81637fe9.png">

2023-04-14 20:49 UTC, six7 requested changes

2023-04-14 20:49 UTC, six7 commented on src/app/components/BranchSelector.tsx
> +  // TODO: I'm not sure there is another way instead of stopImmediatePropagation to prevent option selection when typing the first letter of the option
this seems to select the first item for me as soon as i start typing 

<img width="249" alt="image" src="https://user-images.githubusercontent.com/4548309/232151954-8be66ea5-7718-42f4-9949-76c2857ef5f1.png">

2023-04-14 20:50 UTC, six7 commented on src/app/components/BranchSelector.tsx
> +  // TODO: I'm not sure there is another way instead of stopImmediatePropagation to prevent option selection when typing the first letter of the option
also got an error in console:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/4548309/232152059-2eab0c65-c71f-4de5-8d7a-a2fe1e91b61c.png">

2023-04-17 03:01 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
> +  // TODO: I'm not sure there is another way instead of stopImmediatePropagation to prevent option selection when typing the first letter of the option
Did you upgrade the node module? This error is happening in old version so upgrated it.

2023-04-17 03:02 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
> +  // TODO: I'm not sure there is another way instead of stopImmediatePropagation to prevent option selection when typing the first letter of the option
What I'm not sure is that all test cases are passed with old version but failed with upgraded version.

2023-04-19 19:37 UTC, six7 commented on src/app/components/BranchSelector.tsx
> +  // TODO: I'm not sure there is another way instead of stopImmediatePropagation to prevent option selection when typing the first letter of the option
You're right, this is gone now 👍

2023-04-19 19:38 UTC, six7 commented on src/app/components/BranchSelector.tsx
> +  // TODO: I'm not sure there is another way instead of stopImmediatePropagation to prevent option selection when typing the first letter of the option
i'm still getting that error in the console, i did install, yes

<img width="534" alt="image" src="https://user-images.githubusercontent.com/4548309/233181893-8bd7506d-c86a-415b-9b54-59f0392762c9.png">

2023-04-19 19:39 UTC, six7 requested changes
when you set figma to light mode it currently displays the search field with wrong colors. you can just use raw hex values for these instead, as the context menu has the same colors both in light and dark mode. but create a token for that, so that it's stored in stitches.config

<img width="206" alt="image" src="https://user-images.githubusercontent.com/4548309/233182140-fa5dbf60-f3ff-49d2-8421-64f41dac08b1.png">

2023-04-26 20:21 UTC, six7 commented
just want to check in on this one: is there anything i can help with? as far as i can see its just the error in the console that's still there, the rest is done 🙏

2023-11-27 22:07 UTC, closed without merging