Supernova.io Integration
tokens-studio/figma-plugin pull request #1809
Opened 2023-04-14 13:07 UTC by JiriTrecak

This PR adds support for the Supernova data provider. The provider works analogous to every other git-type provider on the platform, minus the support for branches which is not a concept Supernova has.

An upcoming learning page for this integration [can be found here](https://learn.supernova.io/latest/design-systems/add-design-system-content/tokens-studio.html).

This integration is currently not testable with the production environments of Supernova (we need to merge prod API support for it first), but should be available in next few days as well. In a meantime, I'll share access for the development realm privately.

Start by adding a new provider:

<img width="782" alt="tokens" src="https://user-images.githubusercontent.com/7470393/232052291-4ec4d1f3-0fe1-4fa6-b3f6-2d53dd5a1bf1.png">

2023-04-14 21:10 UTC, six7 requested changes
haven't tested it yet, but here's a preliminary code review that surfaces a couple points. in general let's try to avoid code style changes as these will lead to merge conflicts down the road as we have other dev branches that touch a lot of this stuff as well

2023-04-14 21:10 UTC, six7 commented on src/app/store/remoteTokens.tsx
> +  const pullTokens = useCallback(
any chance we can avoid these large diffs as in code style changes? our `next` branch is quite different from `main`, so i'd like to avoid large merge conflicts due to these

2023-04-14 21:10 UTC, six7 commented on src/app/store/remoteTokens.tsx
> +        case StorageProviderType.SUPERNOVA: {
like ideally this file only adds the supernova stuff, not reshuffles whitespaces entirely (just purely from a merge conflict perspective), but also these should already be linted correctly

2023-04-14 21:10 UTC, six7 commented on src/constants/ErrorMessages.ts
> +  SUPERNOVA_NOT_UPLOADED_YET_ERROR = 'There were no tokens imported from Token Studio to Supernova previously, please push your tokens first',
```suggestion
  SUPERNOVA_NOT_UPLOADED_YET_ERROR = 'There were no tokens imported from Tokens Studio to Supernova previously, please push your tokens first',
```

2023-04-14 21:10 UTC, six7 commented on src/icons/supernova.svg
> +<path d="M16 0H0V16H16V0Z" fill="white"/>
we'd want to make sure this uses `currentColor` as we have to support both light and dark theme

2023-04-14 21:10 UTC, six7 commented on src/storage/SupernovaTokenStorage.ts
> +      console.log(error);
should we track these in Sentry? would help with any issues that might occur

2023-04-14 21:10 UTC, six7 commented on webpack-transform.config.js
> +});
```suggestion
});

```

2023-05-05 16:10 UTC, JiriTrecak commented on src/app/components/PushDialog.tsx
> +    } else if (localApiState && 'designSystemUrl' in localApiState) {
Yes, this is good point. I have changed it :)

2023-05-05 16:11 UTC, JiriTrecak commented on src/app/store/providers/supernova/supernova.tsx
> +      console.log('SYNC TOKENS');
Removed all I could find, I believe rest is there by default now

2023-05-05 16:13 UTC, JiriTrecak commented on src/app/store/remoteTokens.tsx
> +        case StorageProviderType.SUPERNOVA: {
^ Same as above

2023-05-05 16:13 UTC, JiriTrecak commented on src/constants/ErrorMessages.ts
> +  SUPERNOVA_NOT_UPLOADED_YET_ERROR = 'There were no tokens imported from Token Studio to Supernova previously, please push your tokens first',
Good catch - I also found second situation where Token(s) were used incorrectly, fixed both

2023-05-20 09:14 UTC, six7 approved these changes

2023-05-20 09:25 UTC, merged