1874 nextbeta ability to edit theme group name
tokens-studio/figma-plugin pull request #1887
Opened 2023-05-11 09:56 UTC by swordEdge

Uploading 20230511_185431.mp4…

2023-05-11 17:35 UTC, six7 requested changes

2023-05-11 17:35 UTC, six7 commented on src/app/components/ManageThemesModal/ThemeListGroupHeader.tsx
> +  const onMouseEnter = useCallback(() => {
You dont need to do it like this. You can just hide the icon button with display none. On hover of the group set the opacity of the iconbutton to block

2023-05-12 05:46 UTC, six7 approved these changes

2023-05-12 05:46 UTC, six7 commented
@swordEdge just the merge conflict now

2023-05-12 06:40 UTC, swordEdge commented
> @swordEdge just the merge conflict now

2023-05-12 14:00 UTC, merged