feat: ignore first part of token name for variables
tokens-studio/figma-plugin pull request #1992
Opened 2023-06-26 06:43 UTC by mihkeleidast

Applies the same behavior to variables as could be previously done to styles.

Let me know if this should be done differently in some way (e.g. a separate settings value?).

2023-07-26 18:25 UTC, six7 commented
Sorry for the delay on this, we're currently focused on performance. I'll make sure to focus on this for a release after the performance focus is over 🙏

2023-08-22 14:54 UTC, railstride commented
Hey @six7, were you able to make any progress on this? Very keen to "just" check the option rather than rewriting the core of a style dictionary :D

2023-09-01 07:16 UTC, six7 commented
> Hey @six7, were you able to make any progress on this? Very keen to "just" check the option rather than rewriting the core of a style dictionary :D

hey, no, we're still doing the perf release

2023-11-22 09:08 UTC, mihkeleidast commented
@six7 Any updates, when should we expect progress on this? It's getting a bit annoying to have to rely on a feature branch to sync variables properly...

2023-11-22 11:34 UTC, mihkeleidast commented on src/plugin/setValuesOnVariable.test.ts
> +    const settings = { ignoreFirstPartForStyles: true } as SettingsState;
Variables have been in use for quite a while, so making the same setting change behavior may be unexpected. Would it be better to create a new setting for this?

2023-11-22 11:38 UTC, mihkeleidast commented
@six7 Cheers, done! I have one open question regarding whether this feature should use the existing setting, or a new setting?

Also, not sure if I have to do anything to get the failing checks to succeed, does not seem like an issue I have created?

2023-11-23 09:55 UTC, LukeFinch commented
> @six7 Cheers, done! I have one open question regarding whether this feature should use the existing setting, or a new setting?
> 
> Also, not sure if I have to do anything to get the failing checks to succeed, does not seem like an issue I have created?

HI @mihkeleidast I'll check the tests for you. As for whether it should be a new setting. I think for now - let's keep it as a separate setting. It's easier to merge them in the future if we want to. There may also be a discovery benefit from us having it called out individually.

2023-11-23 10:34 UTC, mihkeleidast commented
Refactored it to a separate settings value.

2023-11-26 21:30 UTC, six7 requested changes
Thanks for all this! Code looks fine, but: As you have it right now, this setting will not be remembered each time the user restarts the plugin.

Look into `updateUISettings` to see how we do this, there you'll notice we pass through the `ignoreFirstPartForStyles`. As a user I'd expect to set this once and forget about it, not have to recheck that everytime I need it

2023-11-27 09:04 UTC, six7 approved these changes
Nice, thank you! I'll merge this in - we'll combine that with another release this week

2023-11-27 09:04 UTC, merged

2023-12-11 13:05 UTC, railstride commented
been following this issue and am a bit confused about the current state 😄 
so the branch got merged, then reverted due to a bug of this branch and again merged with the bug fix (1.38.6)
… so the functionality is there, right? Now the UI is still missing the option to actually set this feature, or am I missing something?

2023-12-18 06:06 UTC, esthercheran commented
Hey @railstride we reverted this as it wasn't working as expected some additional work is needed. Will keep you updated.