add id to token
tokens-studio/figma-plugin pull request #2075
Opened 2023-07-18 13:04 UTC by swordEdge

2023-07-20 10:53 UTC, SorsOps requested changes

2023-07-20 10:53 UTC, SorsOps commented on src/utils/updateTokenPayloadToSingleToken.ts
> +    $extensions: {
I see we're missing  `...(payload.$extensions ? {` does this cause an issue if we are inadvertently passed a token without an extension property?

2023-07-20 10:53 UTC, SorsOps commented on src/utils/updateTokenPayloadToSingleToken.ts
> +  id?: string,
Probably makes more sense to have 
```suggestion
  id: string = uuidv4(),
```
then we don't have to fix the old calls to this function

2023-07-20 10:53 UTC, SorsOps commented on src/app/store/models/tokenState.tsx
> +      tokens: addIdPropertyToTokesn(data.sets ?? {}) || addIdPropertyToTokesn(state.tokens),
The second part will never fire. This should probably be 
```
addIdPropertyToTokesn(data.sets || state.tokens),
```

2023-07-20 10:55 UTC, SorsOps commented
Failing tests are primarily because of `storeTokenIdInJsonEditor` now being added

2023-07-24 07:56 UTC, swordEdge commented on src/utils/updateTokenPayloadToSingleToken.ts
> +  id?: string,
if we should change the id as default parameter, then when we edit the token, tokenId will be changed. That is not what we expect.

2023-07-24 07:57 UTC, swordEdge commented on src/utils/updateTokenPayloadToSingleToken.ts
> +    $extensions: {
About this comment, rightnow, we added the utility to add Id property to all tokens. In the old version, if the payload doesn't have $extension property, we don't add tokenId. But we should add tokenId even though the payload doesn't have $extensions property.

2023-07-24 09:15 UTC, roppazvan approved these changes
LGTM

2023-07-24 09:27 UTC, merged