resolveTokenValues perf improvements
tokens-studio/figma-plugin pull request #2191
Opened 2023-08-28 07:24 UTC by six7

Fixes https://github.com/tokens-studio/figma-plugin/issues/1755

This pull request involves major changes to the token resolution system, including the addition of a new `TokenResolver` class and the replacement of the old `resolveTokenValues` function with a new `defaultTokenResolver` utility. These changes were made to improve performance and simplify the code. Additionally, some files were modified to remove unused code and simplify logic. It's able to handle deeply nested token sets performantly, as we no longer iterate over all remaining references.

* `src/utils/TokenResolver.ts`: Added a new `TokenResolver` class to resolve tokens and their references efficiently and flexibly in `src/utils/TokenResolver.ts`. (<a href="diffhunk://#diff-b4809e6851ac3bf8ff55467e9606b901d782180f05572177646b5b87641099e8R1-R267">src/utils/TokenResolver.tsR1-R267</a>)
* `src/utils/TokenResolver.test.ts`: Renamed `src/utils/tokenHelpers.test.ts` to `src/utils/TokenResolver.test.ts` and added tests to ensure the `TokenResolver` class can handle complex token structures without causing stack overflows. Also added new tokens and updated imports. (<a href="diffhunk://#diff-0a3339bdfaf2a5f4e6713b9b421551a456db51d5ffe9c106a236eb565cf791e7L440-R502">src/utils/TokenResolver.test.tsL440-R502</a>)
* `src/utils/tokenHelpers.ts`: Simplified and optimized `tokenHelpers.ts` by removing unused functions and imports and replacing them with the new `defaultTokenResolver` utility for more efficient token resolution. (F4d6c2e6L2R2)
* `src/app/store/useTokens.tsx`: Replaced the `resolveTokenValues` function with the new `defaultTokenResolver` in `useTokens.tsx` for improved performance and simplified code. (PR #X)
* `src/utils/alias/getAliasValue.ts`: Removed logic and comment related to `typography` and `boxShadow` values in `getAliasValue` function to simplify the code. (src/utils/alias/getAliasValue.ts)

2023-08-30 19:29 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +        const hasFailingReferences = !AliasRegex.test(JSON.stringify(resolvedValue));
Is this correct ? Youre checking to see that no aliases exist by negating the test?

2023-08-30 19:29 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +      // @ts-ignore
This is complaining because its not sure if an array of values is being assigned to say a color token which does not accept it, you would need to assert the type to restrict it to only box shadow in this case

2023-08-30 19:29 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +        if (Object.prototype.hasOwnProperty.call(token.value, key)) {
Does our compile step allow us to prefer to use `key in token.value` for this check instead?

2023-08-30 19:29 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +          // @ts-ignore
Same issue as above for the type check

2023-08-30 19:29 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +      // @ts-ignore
Back to it thinking you might assign a complex non scalar to say a color token

2023-08-30 19:29 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +    // @ts-ignore
We shouldn't need this, you're returning the same token so it fits the schema. It feels like we should add failedToResolve if it manages to get through to here ?

2023-08-30 19:29 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +import { SingleToken } from '@/types/tokens';
Could you run the flamegraph tests and get a benchmark for this change?

2023-08-31 06:17 UTC, six7 commented on src/utils/TokenResolver.ts
> +    const memoKey = token.name || undefined;
On the following lines we pass in a recursive function where we construct a token just by value:

https://github.com/tokens-studio/figma-plugin/blob/28f94f60f8373671b3b40c3ab6620e99ff2af3a8/src/utils/TokenResolver.ts#L241
https://github.com/tokens-studio/figma-plugin/blob/28f94f60f8373671b3b40c3ab6620e99ff2af3a8/src/utils/TokenResolver.ts#L210
https://github.com/tokens-studio/figma-plugin/blob/28f94f60f8373671b3b40c3ab6620e99ff2af3a8/src/utils/TokenResolver.ts#L79
https://github.com/tokens-studio/figma-plugin/blob/28f94f60f8373671b3b40c3ab6620e99ff2af3a8/src/utils/TokenResolver.ts#L86

We do this because of array or object based values, or values inside color modifiers. Those don't have a name, so we can't save them to cache

2023-08-31 06:17 UTC, six7 commented on src/utils/TokenResolver.ts
> +    if (typeof token.value === 'string' || typeof token.value === 'number') {
Great catch, I'll remove

2023-08-31 06:26 UTC, six7 commented on src/utils/TokenResolver.ts
> +class TokenResolver {
that makes sense, and would further speed up loading time of sets. We could display tokens with the raw values where references are unpopulated. We'd then trigger async resolution that would populate the values as they come. I think this does require a bit of a bigger refactor of how we store token values, though 🤔

2023-08-31 06:28 UTC, six7 commented on src/utils/TokenResolver.ts
> +        if (token?.$extensions?.['studio.tokens']?.modify?.type === ColorModifierTypes.MIX) {
those are covered on this line:

https://github.com/tokens-studio/figma-plugin/blob/28f94f60f8373671b3b40c3ab6620e99ff2af3a8/src/utils/TokenResolver.ts#L85

2023-08-31 06:29 UTC, six7 commented on src/utils/TokenResolver.ts
> +          if (typeof resolvedTokenValue.value === 'undefined' || resolvedTokenValue.value === '') {
no, i think you're right. we return an empty string if it's a circular reference (and capture that before)

2023-08-31 06:36 UTC, six7 commented on src/utils/TokenResolver.ts
> +          const parsedValue = resolvedTokenValue.failedToResolve ? resolvedTokenValue.value : this.calculateTokenValue({ ...resolvedTokenValue } as SingleToken, resolvedReferences);
you're right, calculation happens further down, this step is unnecessary

2023-08-31 06:39 UTC, six7 commented on src/utils/TokenResolver.ts
> +            resolvedValue = (typeof resolvedValue === 'string' && (typeof parsedValue === 'string' || typeof parsedValue === 'number')) ? resolvedValue.replace(reference, parsedValue) : parsedValue;
when we check for `(typeof finalValue === 'string' && (typeof parsedValue === 'string' || typeof parsedValue === 'number'))` we kind of know that `parsedValue` will never be undefined right? as it must be either a string or a number

2023-08-31 08:20 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +    const memoKey = token.name || undefined;
Ahh makes sense , yeah those are ephemeral and we shouldn't cache

2023-08-31 08:26 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +            resolvedValue = (typeof resolvedValue === 'string' && (typeof parsedValue === 'string' || typeof parsedValue === 'number')) ? resolvedValue.replace(reference, parsedValue) : parsedValue;
Yeah our logic feels sound , but the typing of the return for calculatedTokenValue tells the system that it could be undefined as a possibility

2023-08-31 16:26 UTC, six7 commented on src/utils/TokenResolver.ts
> +        const hasFailingReferences = !AliasRegex.test(JSON.stringify(resolvedValue));
It should be ! I just talked to Copilot and he explained it to me :D 

I understand your confusion. Let me clarify how the hasFailingReferences boolean works.

The purpose of the hasFailingReferences boolean is to determine whether the finalValue of a token contains any references to other tokens that have not been resolved. If finalValue contains any references to other tokens that have not been resolved, hasFailingReferences will be true. If finalValue does not contain any references to other tokens that have not been resolved, hasFailingReferences will be false.

The AliasRegex regular expression pattern is used to match any references to other tokens in the finalValue of a token. If finalValue contains any references to other tokens that have not been resolved, AliasRegex.test(finalValue) will return true, indicating that the regular expression pattern has been matched. If finalValue does not contain any references to other tokens that have not been resolved, AliasRegex.test(finalValue) will return false, indicating that the regular expression pattern has not been matched.

2023-08-31 16:28 UTC, six7 commented on src/utils/TokenResolver.ts
> +        if (Object.prototype.hasOwnProperty.call(token.value, key)) {
no, `using ForInStatement is not allowed`

2023-08-31 16:44 UTC, six7 commented on src/utils/TokenResolver.ts
> +import { SingleToken } from '@/types/tokens';
i ran them locally, but nothing was commited. not sure if that did anything?

2023-08-31 16:44 UTC, six7 commented on src/utils/TokenResolver.ts
> +      // @ts-ignore
fixed

2023-08-31 16:44 UTC, six7 commented on src/utils/TokenResolver.ts
> +          // @ts-ignore
fixed

2023-08-31 16:44 UTC, six7 commented on src/utils/TokenResolver.ts
> +            const parsedValue = this.calculateTokenValue({ value: tokenValueWithoutProperty[propertyName] } as SingleToken, resolvedReferences);
fixed

2023-08-31 16:44 UTC, six7 commented on src/utils/TokenResolver.ts
> +            resolvedValue = (typeof resolvedValue === 'string' && (typeof parsedValue === 'string' || typeof parsedValue === 'number')) ? resolvedValue.replace(reference, parsedValue) : parsedValue;
fixed!

2023-08-31 16:44 UTC, six7 commented on src/utils/TokenResolver.ts
> +          if (typeof resolvedTokenValue.value === 'undefined' || resolvedTokenValue.value === '') {
fixed

2023-08-31 16:45 UTC, six7 commented on src/utils/TokenResolver.ts
> +  public setTokens(tokens: SingleToken[]): ResolveTokenValuesResult[] {
lets do this in a followup as discussed, i totally agree

2023-09-01 05:16 UTC, SorsOps commented on src/utils/TokenResolver.ts
> +import { SingleToken } from '@/types/tokens';
@six7  I ran the benchmark tests. It could be a false positive, but it looks like we regressed in performance for most cases

2023-09-04 07:02 UTC, SorsOps requested changes

2023-09-04 07:22 UTC, six7 commented on src/utils/TokenResolver.ts
> +          if (typeof resolvedTokenValue.value === undefined) {
fixed it now and changed in other occurences in this file too

2023-09-04 07:41 UTC, merged