1821 cant rename stylesvariables after changing the parent name of a token group
tokens-studio/figma-plugin pull request #2259
Opened 2023-09-21 10:33 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/262ddee1-7d21-4cf5-b324-04f9facd069e

2023-09-21 19:13 UTC, six7 requested changes

2023-09-21 19:13 UTC, six7 commented on src/app/store/models/reducers/tokenState/renameStyleIdsToCurrentTheme.ts
> +  const oldNameMapNewName = tokensToRename.reduce<Record<string, string>>((acc, curr) => {
Instead of building the object like this here, why don't we just pass the object in like that? Instead of passing in an array like now. That would make the code more readable IMO

2023-09-21 19:13 UTC, six7 commented on src/app/components/EditTokenForm.tsx
> +              renameStylesFromTokens([{ oldName, newName }], activeTokenSet);
Like here, why don't we just do an object with `{ oldName: newName }` ?

2023-09-25 09:52 UTC, keeganedwin commented
Tested and confirming that this works when renaming the parent level of a token-group, then checking `sync variables` & `sync styles` in the modal which results in successful renaming. Even maintains the connection after renaming on elements that have variables or styles applied.

2023-10-02 06:56 UTC, robinhoodie0823 commented on src/app/store/models/reducers/tokenState/renameStyleIdsToCurrentTheme.ts
> +  const oldNameMapNewName = tokensToRename.reduce<Record<string, string>>((acc, curr) => {
The structure of `renameStylesFromTokens` has been designed to get array params which can handle multiple styles changes. So it would be better to use array params.

2023-10-02 06:56 UTC, robinhoodie0823 commented on src/app/components/EditTokenForm.tsx
> +              renameStylesFromTokens([{ oldName, newName }], activeTokenSet);
And here the same reason.

2023-10-02 19:47 UTC, closed without merging