1930 active theme disabled upon editing and saving
tokens-studio/figma-plugin pull request #2261
Opened 2023-09-22 22:51 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/8f011893-9678-4a00-9c31-bd1325a4f037

2023-09-24 15:48 UTC, six7 commented on src/app/store/models/reducers/tokenState/saveTheme.ts
> +  if (!isActiveTheme) {
were we just doing it wrong before? or why is the fix to this so simple? any side effects that could be caused?

2023-09-25 09:36 UTC, keeganedwin commented
Tested and confirming that this works when:
1. Editing theme name 
2. Editing set status: source, enabled, disabled.

2023-10-02 00:09 UTC, robinhoodie0823 commented on src/app/store/models/reducers/tokenState/saveTheme.ts
> +  if (!isActiveTheme) {
Yes. The root cause was when try to edit active theme, then it all clears its activity inside the condition.

2023-10-02 06:32 UTC, six7 requested changes
can you base the change on `main` and not `epic/performance` ? may be best to redo the branch given the change is so small

2023-10-04 08:12 UTC, closed without merging