2151-adjust-shorthand-for-quick-edit-on-windows-to-ctrl+click
tokens-studio/figma-plugin pull request #2267
Opened 2023-09-26 02:04 UTC by robinhoodie0823

2023-09-26 20:15 UTC, six7 requested changes

2023-09-26 20:15 UTC, six7 commented on src/app/components/MoreButton/MoreButton.tsx
> +    if (event.metaKey || event.ctrlKey) {
i think this wont work as it will disable `ctrl + click` on macos which is often used to right-click the context menu.

can we not check the operating system somehow?

2023-09-27 14:55 UTC, six7 requested changes

2023-09-27 14:55 UTC, six7 commented on src/app/components/MoreButton/MoreButton.tsx
>        handleEditClick();
test

2023-09-29 07:37 UTC, SorsOps commented on src/app/components/MoreButton/MoreButton.tsx
> +    if (event.metaKey || event.ctrlKey) {
hmmm, we should be able to do this with 
`const isMacBrowser = /Mac|iPod|iPhone|iPad/.test(navigator.platform);`

I'm just not sure if this is exposed correctly in the electron wrapper, we would need to verify

2023-09-29 16:26 UTC, six7 approved these changes

2023-09-29 16:32 UTC, closed without merging