Add rotation property to number & dimension tokens
tokens-studio/figma-plugin pull request #2285
Opened 2023-10-01 02:40 UTC by LukeFinch

Currently, we can't set the rotation of a layer with a token.
This PR adds a new rotation property to numbers and dimensions.

<img width="862" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/23120116/601fe173-a0b4-4d3a-95c9-eaf2f8123943">

Rotation happens around the centre point of the layer - emulating the behaviour of setting the behaviour in the UI.

Do we wish to have these appear on dimension tokens?
Currently, dimension forces a unit - px or rem.
Rotation should be in degrees or radians, units we don't currently support.

2023-10-02 06:31 UTC, six7 requested changes

2023-10-02 06:31 UTC, six7 commented on src/app/hooks/usePropertiesForType.test.ts
> +        },
Let's remove those from `dimension`. `rotation` is not a valid dimension unit, let's just keep it in `number`.

2023-10-02 06:31 UTC, six7 commented on src/app/hooks/usePropertiesForType.ts
> +          },
This currently also makes it appear for `dimension`. Let's change it so it only appears for `number`.

2023-10-02 06:31 UTC, six7 commented on src/plugin/removeValuesFromNode.ts
> +      if ('relativeTransform' in node && typeof node.relativeTransform !== 'undefined') {
are we able to change rotation for instances / instance children? or would that lead to an error?

2023-10-02 06:31 UTC, six7 commented on src/plugin/rotateNodes.test.ts
> +    rotateNode(node, '45px');
this feels wrong. why would we want to use 45px as a rotation?

2023-10-02 10:19 UTC, six7 commented on package-lock.json
@LukeFinch can you remove this one? Given we didnt install anything this feels like a mistake

2023-10-03 11:56 UTC, LukeFinch commented on src/plugin/removeValuesFromNode.ts
> +      if ('relativeTransform' in node && typeof node.relativeTransform !== 'undefined') {
Oooh this is a very good point! It would lead to an error.
How's best to handle those kinds of errors? - I guess its the same as trying to change the size on an instance's child?

2023-10-03 12:04 UTC, LukeFinch commented on src/plugin/rotateNodes.test.ts
> +    rotateNode(node, '45px');
Yeah this is a little wrong.
It seems like the number tokens are passing a string when they get sent across, and we need to parse them back into numbers.  This should really be '45' not '45px' to catch this issue

2023-10-03 13:09 UTC, LukeFinch commented on package-lock.json
Not sure how it ended up changing. But resolved.

2023-12-28 10:09 UTC, six7 commented
@LukeFinch can you get a changeset in this one and then resolve the merge conflict? then let's get that merged

2024-01-03 12:39 UTC, six7 approved these changes

2024-01-03 12:40 UTC, merged