1821-cant-rename-stylesvariables-after-changing-the-parent-name-of-a-token-group
tokens-studio/figma-plugin pull request #2293
Opened 2023-10-02 19:48 UTC by robinhoodie0823

2023-10-03 06:34 UTC, six7 requested changes

2023-10-03 06:34 UTC, six7 commented on src/app/components/DownshiftInput/mentions.css
> +  background: var(--colors-contextMenuBg);
this seems like a mistake, we only recently changed this

2023-10-03 06:34 UTC, six7 commented on src/app/store/models/reducers/tokenState/renameVariableNamesToThemes.ts
>      }
lets rename this variable to something more understandable: `oldToNewNameMap` for example

2023-10-03 06:42 UTC, robinhoodie0823 commented on src/app/components/DownshiftInput/mentions.css
> +  background: var(--colors-contextMenuBg);
Reverted.

2023-10-03 06:42 UTC, robinhoodie0823 commented on src/app/store/models/reducers/tokenState/renameVariableNamesToThemes.ts
>      }
Updated variable name to `oldToNewNameMap`

2023-10-04 06:47 UTC, six7 approved these changes

2023-10-04 06:52 UTC, merged