1935-unable-to-remove-license-key-rebase
tokens-studio/figma-plugin pull request #2294
Opened 2023-10-03 01:49 UTC by robinhoodie0823

2023-10-03 06:45 UTC, SorsOps commented on src/app/components/AddLicenseKey/AddLicenseKey.tsx
> +            value={
Instead of using this hardcoded value, can we instead use null and the empty string to properly distinguish between the two ?

2023-10-03 06:51 UTC, robinhoodie0823 commented on src/app/components/AddLicenseKey/AddLicenseKey.tsx
> +            value={
@SorsOps I also tried to use `null` and empty string to distinguish the two situations. But the empty string automatically converted to `null` and it's difficult to distinguish by using the two values you proposed. That is why I used the hardcoded value.

2023-10-05 06:42 UTC, six7 requested changes

2023-10-05 06:42 UTC, six7 commented on src/app/components/AddLicenseKey/AddLicenseKey.tsx
> +            value={
can you change the logic in `[removeLicenseKey](https://github.com/tokens-studio/figma-plugin/blob/abf1cb0be9605817287f1e988e84529793cfb902/src/app/store/models/userState.ts#L128)` so it takes the string as optional?

if there is a license key, we trigger `[removeLicense](https://github.com/tokens-studio/figma-plugin/blob/abf1cb0be9605817287f1e988e84529793cfb902/src/app/store/models/userState.ts#L132C38-L132C38)` on line 132 of `userState.tsx

and then we continue as before, we reset the local license key.

that would mean we dont need to pass `empty`, and we would still try to detach the key, but it is no longer a requirement. we would still continue with clearing the key locally, which is what they want to do.

2023-10-06 06:12 UTC, SorsOps commented on src/app/components/AppContainer/startupProcessSteps/addLicenseFactory.ts
> +    const { islicenseKeyRemoved } = params;
This feels weird that we're tracking the licence key being removed instead of the initial loading  ? We never actually change the value of isLicenseKeyRemoved, so it feels kind of messy that we have 

1. The initial load (assuming empty)
2. Adding a key
3. A user removes the licence key 

If a user restarts now we have stored the isLicenseKeyRemoved value and the startup logic is now different. I feel like we should rather send an `initialLoad` state var, and then have a side effect of turning this off after we perform the first execution of this function

2023-10-06 08:44 UTC, SorsOps commented on src/app/components/AppContainer/startupProcessSteps/addLicenseFactory.ts
> +    if (licenseKey === null && initialLoad.toString() !== 'true') {
Can't we do something like ` if ((licenseKey === null|| licenseKey ===undefined) && !initialLoad) {`

Or do we gain anything from the stringification of the boolean value ?

2023-10-06 09:14 UTC, robinhoodie0823 commented on src/app/components/AppContainer/startupProcessSteps/addLicenseFactory.ts
> +    if (licenseKey === null && initialLoad.toString() !== 'true') {
The value of `initialLoad` that we get is the string type.

2023-10-06 09:16 UTC, SorsOps commented on src/app/components/AppContainer/startupProcessSteps/addLicenseFactory.ts
> +    const { initialLoad } = JSON.parse(JSON.stringify(params));
Why are we doing this ? This should result in no change

2023-10-06 09:23 UTC, robinhoodie0823 commented on src/app/components/AppContainer/startupProcessSteps/addLicenseFactory.ts
> +    const { initialLoad } = JSON.parse(JSON.stringify(params));
Resolved.

2023-10-06 09:24 UTC, SorsOps approved these changes

2023-10-08 17:16 UTC, six7 approved these changes

2023-10-08 17:29 UTC, merged