When switching themes switch the figma native theme mode selector if possible
tokens-studio/figma-plugin pull request #2336
Opened 2023-10-25 17:38 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/8769ec50-0d13-4b1c-9d0a-6797e8f65115

2023-10-26 10:23 UTC, SorsOps requested changes

2023-10-26 10:23 UTC, SorsOps commented on src/AsyncMessageChannel.ts
> +                const { activeTheme } = msg.message;
```suggestion
                  const { activeTheme, themes } = msg.message;
```

2023-10-26 10:23 UTC, SorsOps commented on src/AsyncMessageChannel.ts
> +                const { themes } = msg.message;
```suggestion
const themeToFind = Object.values(activeTheme)[0];
```

2023-10-26 10:23 UTC, SorsOps commented on src/AsyncMessageChannel.ts
> +                const activeMode = themes.filter((theme) => theme.id === Object.values(activeTheme)[0])[0];
```suggestion
                const activeMode = themes.find((theme) => theme.id === themeToFind);
```

2023-10-26 10:25 UTC, SorsOps commented
Can you add a changeset so we can inform the users about this change?

Check to see if the fixes for the lookup fix the OOM error, otherwise we'll have to double check why that's occurring

2023-11-10 16:35 UTC, six7 commented
Tests are failing here

2024-01-10 12:52 UTC, six7 requested changes

2024-01-10 12:52 UTC, six7 commented on src/AsyncMessageChannel.ts
> +            if (msg.message.type === 'async/get-theme-info') {
i dont think this belongs here. this file doesnt have any of the other message handlers, this needs to go elsewhere where we define those.

https://github.com/tokens-studio/figma-plugin/blob/1424c9f8e3c8959e4595d5a7a97d7309a0fdf67f/src/app/components/Initiator.tsx#L31

this feels like the right place

2024-01-10 12:52 UTC, six7 commented on src/AsyncMessageChannel.ts
> +                    frame.setExplicitVariableModeForCollection(activeMode?.$figmaCollectionId ?? '', activeMode?.$figmaModeId ?? '');
yeah it could be that the information is outdated and then this will error. they'll likely not be invalid or null but it could be that it doesnt exist anymore causing an error.

let's check for if a) those are set and b) wrap so that we dont crash

2024-01-10 12:52 UTC, six7 commented on src/AsyncMessageChannel.ts
> +                  figma.currentPage.children.forEach((frame) => {
this ignores the issue requirement completely and sets an active variable mode for **every** frame on the current page. this is not what we need. we need to apply way more logic here than that.

https://github.com/tokens-studio/figma-plugin/issues/2187

the issue states that it should have different behavior depending on the apply mode

2024-01-10 12:52 UTC, six7 commented on src/AsyncMessageChannel.ts
> +                const themeToFind = Object.values(activeTheme)[0];
we do not just want to switch the first theme, but all theme groups that are active

2025-09-16 20:20 UTC, closed without merging