Some tokens are falsely labeled as broken
tokens-studio/figma-plugin pull request #2340
Opened 2023-10-27 19:11 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/86917098-1cba-48e8-a937-5d8e5e92cacc

2023-10-29 08:56 UTC, SorsOps commented
@robinhoodie0823 Can you provide the testing for this PR inside for a valid case where the resolution algorithm  is showing a falsely labelled broken token ? This just looks like a PR regressing the functionality to ever show an example of a broken reference

2023-11-10 16:36 UTC, six7 commented
Tests are failing here

2023-11-20 07:38 UTC, six7 commented
@robinhoodie0823 any updates on this one?

2023-11-20 07:55 UTC, robinhoodie0823 commented
No, I'm working on other tickets now. I will fix asap.

2023-11-21 07:49 UTC, six7 requested changes
As @SorsOps already stated we need a test for this scenario. 

Also, it seems you only removed the check if something is failing. What needs to be fixed is the fact that some tokens are falsely labeled as broken, not that we dont want tokens to show up as broken anymore.

The problem according to the issue is about typography, border, shadow tokens.

2023-11-21 07:49 UTC, six7 commented on src/utils/TokenResolver.test.ts
> -    failedToResolve: true,
Why remove this? This token should be classified as failedToResolve because it did fail to resolve. We cant just remove this.

2023-11-21 07:49 UTC, six7 commented on src/utils/TokenResolver.ts
>          // If it's not, we mark it as failed to resolve
We cant uncomment this. This is important to understand that some tokens failed to resolve.

2023-11-21 07:49 UTC, six7 commented on src/utils/TokenResolver.ts
>          resolvedToken = {
Same here, we need hasFailingReferences.

2023-11-25 08:27 UTC, six7 requested changes

2023-11-25 08:27 UTC, six7 commented on src/utils/TokenResolver.ts
> +        const convertedValue = stringifiedValue.substring(1, stringifiedValue.length - 1);
I think this won't work for tokens that have another object inside, such as composite tokens or shadow tokens. Is there another way you can stringify the object that does not produce curly brackets?

For example right now the transformer tests are failing because of this

2023-11-29 07:36 UTC, six7 approved these changes
✨

2023-11-29 08:10 UTC, merged