Gitlab issue connecting to repo
tokens-studio/figma-plugin pull request #2354
Opened 2023-11-02 13:42 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/80fcb735-5877-4991-846e-5bd150934e4e

2023-11-03 01:30 UTC, SorsOps requested changes

2023-11-03 01:30 UTC, SorsOps commented on src/storage/GitlabTokenStorage.ts
> +    });
We need a fix on the test file here for the mock as its no longer `@gitbeaker/browser` and now `@gitbeaker/rest`

2023-11-07 11:44 UTC, six7 reviewed
Recent changes look good, but tests are failing still.

2023-11-07 12:19 UTC, SorsOps approved these changes

2023-11-07 12:19 UTC, merged