Values are not respected in variables
tokens-studio/figma-plugin pull request #2366
Opened 2023-11-13 03:20 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/29107673-ab3d-4775-81c3-129d575eb38b

2023-11-13 07:55 UTC, six7 requested changes
can you also link the issue?

2023-11-13 07:55 UTC, six7 commented on src/app/components/MoreButton/MoreButton.tsx
> +    console.log('handleEditClick in MoreButton');
log

2023-11-13 07:55 UTC, six7 commented on src/app/store/useTokens.tsx
> +      for (let i = 0; i < tokenItem.length; i += 1) {
I don't think this is how it should be done. https://github.com/tokens-studio/figma-plugin/pull/2366/files#diff-874132b880f3e22690900909f69048afec5f0ec0137e7ae8dbe6c56cbb2628f3R301-R307

here's where we fetch the resolved tokens from the store, no need to manually iterate over them

2023-11-13 07:55 UTC, six7 commented on src/plugin/figmaTransforms/colors.ts
> +    console.log('starts with rgb');
log

2023-11-13 07:55 UTC, six7 commented on src/plugin/figmaTransforms/colors.ts
> +    console.log('starts with hsl');
log

2023-11-13 07:55 UTC, six7 commented on src/plugin/figmaTransforms/colors.ts
> +    console.log('else case');
log

2023-11-13 07:55 UTC, SorsOps commented on src/app/components/MoreButton/MoreButton.tsx
> +    console.log('handleEditClick in MoreButton');
Remove

2023-11-13 07:55 UTC, SorsOps commented on src/app/store/useTokens.tsx
> +    Object.values(tokens).forEach((tokenItem) => {
This is mutating the data which we shouldn't be doing as then the tokens are changed when using the createVariables side effect. If we're going to make changes here for the create local variables usage we should be cloning the tokens to not get any unintentional changes in the data elsewhere

2023-11-13 07:55 UTC, SorsOps commented on src/plugin/figmaTransforms/colors.ts
> +    console.log('starts with rgb');
Remove console logs

2023-11-13 07:55 UTC, SorsOps commented on src/utils/TokenResolver.ts
> -          console.log('Circular reference detected:', path);
Restore this to help with debugging

2023-11-13 07:55 UTC, SorsOps commented on src/app/store/useTokens.tsx
>      const createVariableResult = await wrapTransaction({
Can we get a test on this to verify its working ?

2023-11-22 12:52 UTC, SorsOps commented on src/app/store/useTokens.test.tsx
> +          { name: 'color', value: '#1450c8', type: TokenTypes.COLOR },
Why did this value change?

2023-11-22 12:52 UTC, SorsOps commented on src/app/store/useTokens.tsx
> +        const resolvedValue = getAliasValue(tokenItem, tokensContext.resolvedTokens) || '';
I still can't really see a new test that confirms this behaviour ?

2023-11-27 08:00 UTC, SorsOps approved these changes

2023-11-27 19:26 UTC, six7 approved these changes

2023-11-29 08:10 UTC, merged