For-multi-value-number-or-dimension-or-spacing-or-sizing-tokens-we-should-skip-them
tokens-studio/figma-plugin pull request #2368
Opened 2023-11-14 08:07 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/41b901f1-35cb-4b63-ae1f-66bd05c02965

2023-11-15 07:06 UTC, SorsOps requested changes

2023-11-15 07:06 UTC, SorsOps commented on src/app/store/useTokens.tsx
> +    Object.keys(tokens).forEach((tokenSetKey) => {
We can do all of this cleaner with a `Object.entries(tokens).reduce(...)`

2023-11-15 07:06 UTC, SorsOps commented on src/app/store/useTokens.tsx
> +
Can you link the ticket for this PR? I just want to double check the context

2023-11-15 07:06 UTC, SorsOps commented on src/app/store/useTokens.tsx
> +          return !resolvedValue.toString().trim().includes(' ');
Can we test this function to assert that this is processing the tokens correctly ?

2023-11-15 07:06 UTC, SorsOps commented on src/app/store/useTokens.tsx
> +
We should also add a changeset to indicate this fix for the users

2023-11-18 14:14 UTC, SorsOps commented on src/app/store/useTokens.test.tsx
> +  // it('remapTokensInGroup', async () => {
Can we turn these back on ?

2023-11-18 14:18 UTC, SorsOps commented on src/app/store/useTokens.tsx
> +          const resolvedValue = getAliasValue(tokenItem.value, tokensContext.resolvedTokens) || '';
Should we not be filtering based on the type of token as well. The linked issue describes its usage for dimension and sizing ,other token types will likely be allowed to have spaces in them

2023-11-21 07:45 UTC, six7 approved these changes

2023-11-21 07:46 UTC, six7 requested changes

2023-11-21 07:46 UTC, six7 commented on src/app/store/useTokens.test.tsx
> +    it('skip multi value tokens', async () => {
Can you add a multi value token here to see it gets filtered out? and one `TEXT` token that also has a space inside but is not getting filtered out due to the type?

2023-11-21 08:00 UTC, SorsOps commented on src/app/store/useTokens.tsx
> +    const validTokenTypes = [TokenTypes.DIMENSION, TokenTypes.BORDER_RADIUS, TokenTypes.BORDER, TokenTypes.BORDER_WIDTH, TokenTypes.SPACING];
This can just be a constant , we don't need to place this on the stack each time we call this function

2023-11-21 08:21 UTC, robinhoodie0823 commented on src/app/store/useTokens.test.tsx
> +    it('skip multi value tokens', async () => {
You mean, I need to add other multi value tokens besides the `SPACING` token?

2023-11-21 12:32 UTC, six7 commented on src/app/store/useTokens.test.tsx
> +    it('skip multi value tokens', async () => {
ah, i didnt see that you had one in there already. i think the tests could use a specific example.

here you have it:

```
            { name: 'spacing-1', value: '{base.base-50} {base.base-150}', type: TokenTypes.SPACING },
```

if it was just 3 tokens instead of 30 then the test would be more readable

2023-11-21 20:31 UTC, six7 approved these changes

2023-11-22 06:47 UTC, SorsOps approved these changes

2023-11-22 06:47 UTC, merged