refactor displaying stroke in the inspect tab
tokens-studio/figma-plugin pull request #2408
Opened 2023-12-05 09:01 UTC by robinhoodie0823

2023-12-05 21:24 UTC, six7 requested changes
Can you also add a test to make sure this new code is covered?

2023-12-05 21:24 UTC, six7 commented on .changeset/empty-garlics-share.md
> +Refactor the bug that stroke is not displayed in the inspect tab.
```suggestion
Inspect now also properly shows stroke variables that were applied
```

2023-12-05 21:24 UTC, six7 commented on src/constants/Properties.ts
> +  stroke = 'stroke',
This should be borderColor - which we already have further above

2023-12-05 21:24 UTC, six7 commented on src/plugin/getAppliedVariablesFromNode.ts
> +              type: Properties.stroke,
This could use the borderColor property instead

2023-12-05 21:24 UTC, six7 commented on src/plugin/getAppliedVariablesFromNode.ts
> +  console.log('local variables', localVariables);
Log

2023-12-07 09:22 UTC, six7 approved these changes

2023-12-07 09:55 UTC, esthercheran commented
It is working as expected functionally

2023-12-08 05:44 UTC, esthercheran approved these changes

2023-12-08 07:47 UTC, merged