2353-unable-to-un-apply-tokens-on-multiple-layers-at-once
tokens-studio/figma-plugin pull request #2418
Opened 2023-12-09 15:54 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/5278d16c-b8ff-48d6-a92a-d937004a9cb3

2023-12-10 18:32 UTC, six7 requested changes

2023-12-10 18:32 UTC, six7 commented on src/plugin/updatePluginDataAndNodes.test.ts
> +    console.log('figmaStyleMaps: ', figmaStyleMaps);
logs

2023-12-10 18:32 UTC, six7 commented on src/plugin/updatePluginDataAndNodes.ts
> -              delete tokenValues[key as CompositionTokenProperty];
can you explain why this was removed?

2023-12-10 18:33 UTC, six7 commented on src/plugin/updatePluginDataAndNodes.ts
> -              delete tokenValues[key as CompositionTokenProperty];
or why that particular change caused the bug to go away?

2023-12-13 17:44 UTC, robinhoodie0823 commented on src/plugin/updatePluginDataAndNodes.ts
> -              delete tokenValues[key as CompositionTokenProperty];
In case of multiple layer or nodes, it needs user action needs to be applied to all of them.
But since the user action would be removed here, it could only applied to one node.

2023-12-18 08:08 UTC, six7 approved these changes

2023-12-18 08:31 UTC, merged

2023-12-18 10:04 UTC, esthercheran reviewed
Feature is working as expected.