Border token color not linking to style
tokens-studio/figma-plugin pull request #2431
Opened 2023-12-15 07:39 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/79ce6a2e-8acb-47df-a259-fd1417cefc6c

2023-12-15 20:17 UTC, six7 commented on src/plugin/setValuesOnNode.ts
> +        const borderColorData = data.borderColor?.replace('{', '').replace('}', '') as string;
when we apply a token to a layer we dont have references anymore. why is this step required?

2023-12-16 07:43 UTC, esthercheran reviewed
Working as expected functionally

2023-12-18 08:43 UTC, keeganedwin commented
@esthercheran @six7 
When applying a border token that is using `reference mode`, it is not connected to a style as expected; input mode however works as of now:
[Example video](https://github.com/tokens-studio/figma-plugin/assets/93133012/cc5d743a-4fdd-48cc-bbd1-c4a6b9c758ab
)

2023-12-18 09:07 UTC, robinhoodie0823 commented on src/plugin/setValuesOnNode.ts
> +        const borderColorData = data.borderColor?.replace('{', '').replace('}', '') as string;
The token name which has been stored as `data.borderColor` has the above string type.

2023-12-18 18:57 UTC, six7 commented
> [@esthercheran](https://github.com/esthercheran) [@six7](https://github.com/six7) When applying a border token that is using `reference mode`, it is not connected to a style as expected; input mode however works as of now: [Example video](https://github.com/tokens-studio/figma-plugin/assets/93133012/cc5d743a-4fdd-48cc-bbd1-c4a6b9c758ab)

yeah we'd want that to work too

2023-12-20 12:18 UTC, six7 commented on src/utils/TokenResolver.test.ts
> +    resolvedValueWithReferences: undefined,
can you change the logic so that it does not include this if it is undefined? Then we save a lot of unnecessary additions

2023-12-20 12:19 UTC, six7 commented on src/utils/TokenResolver.test.ts
> +  for (let i = 2; i < 10; i += 1) {
lets leave this at 1000. this is a performance test

2023-12-20 12:19 UTC, six7 commented on src/utils/TokenResolver.test.ts
> +  const deepTokenOutput = [
also change this again to how it was before, the idea of this test is to test dynamically over 1000

2023-12-21 07:52 UTC, six7 requested changes

2023-12-21 07:52 UTC, six7 commented on src/utils/TokenResolver.test.ts
> +    resolvedValueWithReferences: '#ff0000',
This is interesting, the resolved value with references is just red? That's a mistake. The token value is an rgba of red but then just take 0.5 opacity. But the resolved value seems to have lost the red? Seems like there's an issue with the logic somewhere.

2023-12-21 07:52 UTC, six7 commented on src/utils/TokenResolver.test.ts
> +    resolvedValueWithReferences: '0.2 + 0.2',
Same here. The raw value is opacity.default + 0.6, but the resolved value is 0.2 + 0.2?

2023-12-21 07:52 UTC, six7 commented on src/utils/TokenResolver.test.ts
> +    resolvedValueWithReferences: '0.2 + 0.2',
Now this feels out of place. a rgba of a color and opacity leads to 0.2 + 0.2?

2023-12-21 07:52 UTC, six7 commented on src/utils/TokenResolver.test.ts
> +    resolvedValueWithReferences: '{opacity.default} + 0.6',
same here

2023-12-21 07:52 UTC, six7 commented on src/utils/TokenResolver.test.ts
> +    resolvedValueWithReferences: '#00a2ba',
this feels like a mistake again. the raw value is colors.white, the true value is #007182 but the resolved value with references is some other hex string?

2023-12-21 07:52 UTC, six7 commented on src/utils/__tests__/__snapshots__/convertTokensObjectToResolved.test.ts.snap
> +      "resolvedValueWithReferences": undefined,
lets not include undefined resolved value with references in the output

2023-12-21 07:52 UTC, six7 commented on src/utils/__tests__/__snapshots__/convertTokensObjectToResolved.test.ts.snap
> +      "resolvedValueWithReferences": "0.5",
again feels like a mistake. if the token value is `rgba(255, 0, 0, {opacity.medium})` then why is the resolved value 0.5?

2023-12-21 07:52 UTC, six7 commented on src/utils/__tests__/__snapshots__/convertTokensObjectToResolved.test.ts.snap
> +      "resolvedValueWithReferences": "100%",
the token value is `{radii.full} 0%` so why is the resolved value 100%?

2023-12-21 07:52 UTC, six7 commented on src/utils/__tests__/__snapshots__/convertTokensObjectToResolved.test.ts.snap
> +      "resolvedValueWithReferences": "1.5",
value is 4.5, why is the resolved value 1.5?

2023-12-21 07:52 UTC, six7 commented on src/utils/__tests__/__snapshots__/convertTokensObjectToResolved.test.ts.snap
> +      "resolvedValueWithReferences": "100%",
value is 100% 0 why is the resolved value 100%?

2023-12-21 07:52 UTC, six7 commented on token-transformer/output/folder-dark.json
> +      "resolvedValueWithReferences": "#1B1F24"
here the value is `#1b1f2480` - resolved value seems to lose the last 2 characters

2023-12-29 11:09 UTC, six7 approved these changes
Approving from a code side

2024-01-02 09:25 UTC, esthercheran reviewed
Working functionally as expected

2024-01-02 15:58 UTC, merged