2427-renaming-tokens-in-the-other-type-breaks-references
tokens-studio/figma-plugin pull request #2440
Opened 2023-12-27 12:18 UTC by robinhoodie0823

https://github.com/tokens-studio/figma-plugin/assets/103296157/f897fb11-9e83-4bab-a376-fd1e56f75bcf

2023-12-28 00:24 UTC, six7 requested changes

2023-12-28 00:24 UTC, six7 commented on src/app/store/models/tokenState.tsx
> +    updateOtherAliases: (state, data: string[]) => {
i think all of this is not required.

all it takes to fix the issue is https://github.com/tokens-studio/figma-plugin/blob/main/src/app/store/models/tokenState.tsx#L360 and remove the check on type. this function right now looks at the type of the originating group, and only updates those that have the same. if we remove the type check there, that's all we need.

2024-01-04 01:20 UTC, robinhoodie0823 commented on src/app/store/models/tokenState.tsx
> +    updateOtherAliases: (state, data: string[]) => {
I think, what you suggest is to change the tokens in a specific group. But we also have to update tokens which have the changed tokens group as reference. Exactly `Other` type tokens.

2024-01-04 07:21 UTC, six7 commented on src/app/store/models/tokenState.tsx
> +    updateOtherAliases: (state, data: string[]) => {
ah, i see. then we should be able to just add the logic to https://github.com/tokens-studio/figma-plugin/blob/main/src/app/store/models/tokenState.tsx#L409-L442

similar to how `updateAlias` is called from here: https://github.com/tokens-studio/figma-plugin/blob/main/src/app/store/models/tokenState.tsx#L576

2024-01-04 18:33 UTC, six7 requested changes
Just two minor comments 👍

2024-01-04 18:33 UTC, six7 commented on src/app/store/models/tokenState.tsx
> +                      value: token.$extensions['studio.tokens'].modify.value.replace(data.oldName, data.newName),
The token could also appear not just in the value field but in the 'amount' field (eg for mix modifier or lighten or darken

Lets add that here as well so this is covered too 👍

2024-01-04 18:33 UTC, six7 commented on src/app/store/models/tokenState.tsx
> +            if (token.$extensions?.['studio.tokens'] && token.$extensions?.['studio.tokens'].modify && token.$extensions?.['studio.tokens'].modify.value.includes(data.oldName)) {
Technically if we have a faulty token like

```
studio.tokens: {
  modify: {
    'foo': 'bar'
  }
}
```

Will this crash? We do have the modify field but the value field is not defined. Or do we have a try catch around this?

Maybe add another `?.` just to make sure we dont expect that element to be there

2024-01-08 08:43 UTC, six7 approved these changes

2024-01-08 12:06 UTC, merged