2386 ability to edit tokens to add nested levels
tokens-studio/figma-plugin pull request #2473
Opened 2024-01-22 03:15 UTC by robinhoodie0823

### Why does this PR exist?
User can't edit token to add nested levels.

Closes #2386 

### What does this pull request do?
This PR gives ability to users to add nested levels to a token.

### Testing this change
The current implementation has a if condition to check the new token name starts with one of resolved tokens name to check if token share the same name with group name which is a block to add nested levels.
This PR removes this if condition(it's in `EditTokenForm.tsx`) to give users ability to add nested levels to a token.

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/f2a98cdd-a053-4487-bbea-ca493ff3c733

2024-01-22 07:59 UTC, six7 requested changes

2024-01-22 07:59 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx
> -  const hasPriorTokenName = React.useMemo(
this check had a reason to exist, which we should respect:

When a user has an existing token called `colors.blue.500`, and they create a new token, it cannot begin with the name of a token that already exists, e.g. if a user tried to create `colors.blue.500.primary` - this should not be allowed.

The removal of this code means that users would be able to do this.

The issue at hand describes how users need to be able to do this IF they are editing the token that causes the name collision, so in our example above if they were editing `colors.blue.500` to be renamed to `colors.blue.500.primary`

2024-01-22 07:59 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx
> -  const hasPriorTokenName = React.useMemo(
Copilot suggestion:

```
const hasPriorTokenName = React.useMemo(
  () => {
    const tokensWithSameParent = resolvedTokens.filter((t) => t.internal__Parent === activeTokenSet);
    if (internalEditToken?.status === EditTokenFormStatus.CREATE) {
      // If we are creating a new token, disallow naming it as a prefix of an existing token
      return tokensWithSameParent.find((t) => internalEditToken.name?.startsWith(`${t.name}.`));
    } else if (internalEditToken?.status === EditTokenFormStatus.EDIT) {
      // If we are editing a token, only disallow the name if it's prefix matches another token and it is not the token we are currently editing
      return tokensWithSameParent.find((t) => internalEditToken.name?.startsWith(`${t.name}.`) && internalEditToken.initialName !== t.name);
    }
    return false;
  },
  [internalEditToken, resolvedTokens, activeTokenSet],
);
```

2024-03-05 12:39 UTC, six7 approved these changes
Changes look good from a technical side

2024-03-06 09:58 UTC, esthercheran reviewed
Functionality is working as expected

2024-03-06 10:27 UTC, merged