UI for Variables m2
tokens-studio/figma-plugin pull request #2480
Opened 2024-01-26 11:14 UTC by LukeFinch

### Why does this PR exist?

This includes the main UI pieces for Variables M2
Ready to have the data and actions plumbed in with followup PRs

### What does this pull request do?

### Testing this change

### Additional Notes (if any)

2024-01-26 17:26 UTC, six7 reviewed
looking good!

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ImportedTokensDialog.tsx
> +      size="large"
this should cause a linting error, single quotes should be enforced - does it not for you?

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/InspectorTokenSingle.tsx
> +            <Modal modal={false} title={t('chooseANewTokenForValue', { value: tokenToDisplay?.name || token.value })} size="large" isOpen close={onCancel}>
same

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/PullDialog.tsx
> +          size="large"
everywhere basically

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/Tokens.tsx
> +                <Label css={{ fontSize: '$xxsmall' }}>JSON</Label>
can we make this part of the component? so that we can just pass in a text string as a child instead of wrapping that in a `<Label>`

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/TokensBottomBar.tsx
>            >
why the color and fontsize here?

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx
> +  const treeOrListItems = React.useMemo(() => (
do we need this? think we only display the tree nowadays

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx
> +  const ThemeGroups = React.useMemo(() => {
should we move these to a hook so that this file is a bit cleaner?

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx
> +            { themes.length === 0 ? (
from a code structure perspective it'd make sense to extract these to individual components for better legibility

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx
> +      {/* TODO: Refactor this so the modal lives in its own file? */}
agree!

2024-01-26 17:26 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/options.tsx
> +            <Checkbox id="checkbox-styles-color" checked={exportOptions.styles.color} />
maybe lets add a wrapper component around checkbox and label so that this becomes a bit easier to read?

2024-02-06 07:41 UTC, six7 requested changes
i18n is largely still missing, other than that left a couple of comments. looking good! 🙏

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/ManageStylesAndVariables/UseThemes
remove file

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx
> +              Themes
i18n

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx
> +            <Tabs.Trigger value="useSets">Token Sets</Tabs.Trigger>
i18n

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/ManageStylesAndVariables.tsx
> +      <OptionsModal isOpen={showOptions} title="Manage / Export Options" closeAction={handleCancelOptions} />
i18n

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/docsLinks.tsx
> +export const docsLinks = {
if you merge in the latest `release-139` i created a file for these in `packages/tokens-studio-for-figma/src/constants/docUrls.ts`

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/useExportSetsTab.tsx
> +  const treeOrListItems = React.useMemo(() => (
i think we don't need to differentiate between tree or list. even when users dont have git multi file storage enabled we already show their token sets in a tree on the left. let's always show a tree.

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/useExportSetsTab.tsx
> +            <p>Use Themes (Pro) to create multiple collections of variables or styles for easy switching between design concepts. </p>
i18n

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/useExportThemesTab.tsx
> +    window.open('https://tokens.studio/#pricing-1', '_blank');
you should be able to just use a `Button as="a" href="..." target="_blank"`

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/useOptionsModal.tsx
> +              <LabelledCheckbox id="rules-ignore-first-part" name="rulesIgnoreFirstPart" onChange={handleChangeOption} checked={exportOptions.rulesIgnoreFirstPart} label="Ignore first part of token n
do you need both id and name in these?

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/Modal/Modal.tsx
> +              {showClose && (<IconButton
should this be hidden when `backArrow` is given? i wonder if i'd expect both the arrow and the x to perform the same actions when they are placed?

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/Tokens.tsx
> +                <Label css={{ fontSize: '$xxsmall' }}>JSON</Label>
I also wonder.. is `label` the right thing to use here? there's no form control associated with it. it's likely just a regular text or `Text` that you need here

2024-02-06 07:41 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/WindowResizer.tsx
> +    <div id="corner" onPointerDown={onDown} onPointerUp={onUp} ref={cornerRef} style={{ zIndex: 999 }}>
wonder if you could use a Portal for this, anyway likely something that can be worked on outside of this PR?

2024-02-13 09:53 UTC, six7 reviewed
some minor comments

2024-02-13 10:34 UTC, LukeFinch commented on packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx
> +// @ts-nocheck
Oops, that's an oversight on my end. Doesn't need ignoring. 😅

2024-02-13 10:34 UTC, LukeFinch commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/OptionsModal.tsx
> +                <Box as="img" src="" css={{ borderRadius: '$small' }} />
Need to make some, was going to check in with Sam for some content review

2024-02-14 04:43 UTC, six7 approved these changes
🎉

2024-02-14 09:50 UTC, merged