1974 allow users to select which themes to export as variables
tokens-studio/figma-plugin pull request #2522
Opened 2024-02-29 12:04 UTC by robinhoodie0823

### Why does this PR exist?
The current implementation create all variables from all themes even user changed the selection of themes.

Closes #1974  

### What does this pull request do?
Updated the `handleExportToFigma` function to change when `selectedThemes` changed. And added a `createVariablesFromThemes` function to `useTokens` to create variables from selected themes.

### Testing this change

### Additional Notes (if any)

2024-02-29 13:49 UTC, LukeFinch approved these changes

2024-02-29 13:49 UTC, LukeFinch commented on packages/tokens-studio-for-figma/src/app/components/ManageStylesAndVariables/useExportThemesTab.tsx
> +    console.log('themeId: ', themeId);
can remove

2024-03-01 12:05 UTC, six7 requested changes
@robinhoodie0823 tests are failing here

2024-03-07 19:29 UTC, six7 requested changes

2024-03-07 19:29 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/Settings/Settings.tsx
> +  //     dispatch.settings.setPrefixStylesWithThemeName(!!state);
Why this comment?

2024-03-07 19:29 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/Settings/Settings.tsx
> +  // const handleIgnoreChange = React.useCallback(
Why is this a comment?

2024-03-07 19:29 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/Settings/Settings.tsx
> +// import ignoreFirstPartImage from '@/app/assets/hints/ignoreFirstPartForStyles.png';
Lots of comments here

2024-03-07 23:10 UTC, six7 approved these changes

2024-03-07 23:10 UTC, merged

2024-04-13 17:38 UTC, SamIam4Hyma commented
Added to Featurebase Roadmap-	[❖❇️ Choose which themes to export as styles and variables](https://tokensstudio.featurebase.app/p/choose-which-themes-to-export-as-styles-and-variables)