Feat/819 add themes and tokensetorder
tokens-studio/figma-plugin pull request #2561
Opened 2024-03-29 14:58 UTC by georgebuciuman

### Why does this PR exist?

This is a partial implementation for https://github.com/tokens-studio/studio-app/issues/819

### What does this pull request do?

This PR adds support for:
- retrieving themes from Tokens Studio to the plugin
- retrieving token set order from Tokens Studio to the plugin and update Tokens Studio when updates in the plugin are happening

2024-03-30 09:56 UTC, six7 requested changes
Just a few small comments, overall nice 🎉

2024-03-30 09:56 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/MoreButton/MoreButton.tsx
> +      sourceId: token.$extensions?.['studio.tokens']?.urn,
i think this is a mistake, we dont have any check if we're in tokens studio provider - for all other providers this shouldnt set it as it did before

2024-03-30 09:56 UTC, six7 commented on packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
> +        if (!tokenSet.name) return acc;
can there be a case of a token set not having a name?

2024-03-30 09:56 UTC, six7 commented on packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
> +              $figmaVariableReferences: JSON.parse(JSON.parse(theme?.figmaVariableReferences || '{}')),
i think it could make sense to wrap the whole part here in a try / catch, given json parse could throw an error if we get faulty data back from the api.

2024-04-01 13:13 UTC, georgebuciuman commented on packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
> +              $figmaVariableReferences: JSON.parse(JSON.parse(theme?.figmaVariableReferences || '{}')),
this entire function `getProjectData` is wrapped in try/catch

2024-04-01 13:15 UTC, georgebuciuman commented on packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
> +        if (!tokenSet.name) return acc;
No. But BE type for `name` is `string | null | undefined`. It's the same for all the values. I don't know why but that is how BE sets the types

2024-04-01 13:44 UTC, georgebuciuman commented on packages/tokens-studio-for-figma/src/app/components/MoreButton/MoreButton.tsx
> +      sourceId: token.$extensions?.['studio.tokens']?.urn,
It is used for delete. We need to send the urn to Tokens Studio to be able to delete the token. I could also not send the urn from the button but get it in `tokenState` based on the name and parent. But that would mean one more loop through all the tokens

2024-04-03 06:38 UTC, six7 approved these changes

2024-04-03 09:41 UTC, merged