feat: [819] Add support for themes and groups operations
tokens-studio/figma-plugin pull request #2633
Opened 2024-04-12 17:16 UTC by georgebuciuman

### Why does this PR exist?

Closes https://github.com/tokens-studio/studio-app/issues/819

### What does this pull request do?

Adds support for operations on themes and groups:
- create theme group and theme
- update theme groups and themes
- delete theme groups and themes
- add variable ids and styles ids to themes
- update variable ids and styles ids for themes

2024-04-14 15:27 UTC, six7 requested changes
just that one large file that could use some separation, rest is minor comments 👍

2024-04-14 15:27 UTC, six7 commented on packages/tokens-studio-for-figma/src/storage/TokensStudioTokenStorage.ts
> +        console.log('EDIT_TOKEN', data);
log

2024-04-14 15:27 UTC, six7 commented on packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio.ts
> +    const createdThemeGroup = await pushToTokensStudio({
should we wrap this in a try / catch? what if our api is down?

2024-04-14 15:27 UTC, six7 commented on packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio.ts
> +const getThemeGroupsToUpdate = (themes: ThemeObjectsList, groupIdsMap: Record<string, string>) => {
lets move this out into its own file, this file is already quite huge - i think it could benefit from a bit of separation

2024-04-14 15:27 UTC, six7 commented on packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio.ts
> +  switch (action.type) {
can we somehow turn each action type into its own file? that would help with legibility and maintainability instead of having the file itself be quite large

2024-04-15 09:49 UTC, georgebuciuman commented on packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio.ts
> +    const createdThemeGroup = await pushToTokensStudio({
This is already wrapper in a try/catch for each case inside `TokensStudioTokenStorage`. Do you think another wrapper is needed to tread the error here?

2024-04-15 14:27 UTC, six7 commented on packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio.ts
> +    const createdThemeGroup = await pushToTokensStudio({
No i guess we're fine then. We'd still get specific error messaging right? As in if the backend throws an error we can show that ? Instead of it being a generic error

2024-04-15 14:57 UTC, georgebuciuman commented on packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio.ts
> +    const createdThemeGroup = await pushToTokensStudio({
We get specific errors from BE but I wouldn't show that to the users as we get errors that are not very readable. Right now we only show the errors in the console and don't show the success notification to the users when there is an error. Do you think we should always show the error as a notification to the users?
Errors are something like this: `Error creating theme group in Tokens Studio`, `Error updating token set in Tokens Studio`...

2024-04-17 02:38 UTC, six7 commented on packages/tokens-studio-for-figma/src/storage/tokensStudio/updateThemeGroupsInTokensStudio.ts
> +    const createdThemeGroup = await pushToTokensStudio({
That's fine 👍

2024-04-17 02:41 UTC, six7 approved these changes

2024-04-17 02:41 UTC, merged