2645 20 rename variables non functional 1
tokens-studio/figma-plugin pull request #2670
Opened 2024-04-19 08:07 UTC by robinhoodie0823

### Why does this PR exist?
Current plugin does not update existing variables and styles and does not remove variables and styles without connection.

Closes #2645 

### What does this pull request do?
Added sync functions to sync with all updates.

### Testing this change

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/62e1d675-0d85-4d1f-84a8-44faaa1baa4f

2024-04-19 19:39 UTC, six7 requested changes
left a comment on when and how to call the syncVariables / syncStyles stuff

2024-04-19 19:39 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/store/useTokens.tsx
> +      type: AsyncMessageTypes.SYNC_STYLES,
i just looked into this function. from the code you have provided here it seems like it's running before the function to create styles.

however, if you go look up what SYNC_STYLES actually does, it creates styles as well! https://github.com/tokens-studio/figma-plugin/blob/2645-20-rename-variables-non-functional-1/packages/tokens-studio-for-figma/src/plugin/syncStyles.ts
this is inefficient. we do not want to have two places where we create styles. let's change it so that SYNC_STYLES is really only responsible for deleting and renaming styles that were created.

same for SYNC_VARIABLES: https://github.com/tokens-studio/figma-plugin/blob/2645-20-rename-variables-non-functional-1/packages/tokens-studio-for-figma/src/plugin/syncVariables.ts

we need to be very careful with existing variables. we should follow an order of
- look up existing variables
- rename if needed
- delete those that we will no longer need

AFTER this part
- run create and update variable values function

---

however, currently we seem to be running the create / update part in two entirely different areas of the plugin

2024-04-22 07:45 UTC, robinhoodie0823 commented on packages/tokens-studio-for-figma/src/app/store/useTokens.tsx
> +      type: AsyncMessageTypes.SYNC_STYLES,
If we have to handle `renaming` and `removing` tokens in sync functions, in case of an updated token (with same name), how can we have this case?

2024-04-24 22:03 UTC, six7 requested changes
left a few comments 👍

2024-04-24 22:03 UTC, six7 commented on packages/tokens-studio-for-figma/src/plugin/syncStyles.ts
> +        renamedTokenNames.push(styleSet[style.name].name);
it would be better to perform this on line 67 of this file: https://github.com/tokens-studio/figma-plugin/pull/2670/files#diff-11232dee5def4abae12048db6b327184f8a1dad57746bd2eb2df7535d12d164aR67 where you perform the actual rename. makes more sense.

2024-04-24 22:03 UTC, six7 commented on packages/tokens-studio-for-figma/src/plugin/syncVariables.ts
> +          renamedTokenNames.push(variable.name.split('/').join('.'));
is there a reason to push the variable name here? why not push the `tokenName` that you get from the function props further above?

2024-04-24 22:03 UTC, six7 commented on packages/tokens-studio-for-figma/src/plugin/syncVariables.ts
>            variable.name = path;
so do we perform 2 renames now? i'd say you can remove line 23, 1 rename must be enough?

2024-04-25 09:18 UTC, robinhoodie0823 commented on packages/tokens-studio-for-figma/src/plugin/syncVariables.ts
> +          renamedTokenNames.push(variable.name.split('/').join('.'));
The `tokenName` is updated token name which will be replace the original variable name.
The variable name represent the original token name.

2024-04-25 09:18 UTC, robinhoodie0823 commented on packages/tokens-studio-for-figma/src/plugin/syncVariables.ts
>            variable.name = path;
Only 1 renaming functionality is here. I think

2024-04-30 20:54 UTC, six7 approved these changes

2024-04-30 20:54 UTC, merged