Browser plugin preview
tokens-studio/figma-plugin pull request #2748
Opened 2024-05-13 18:32 UTC by macintoshhelper

### Why does this PR exist?

Closes #0000 

### What does this pull request do?

### Testing this change

### Additional Notes (if any)

2024-05-17 18:47 UTC, six7 requested changes
nice overall! let's hold off merging this until 2.0 is out, too much risk (and its the basis for devex anyway)

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/preview.tsx
> +          paddingRight: 8,
```suggestion
          paddingTop: '$2',
          paddingBottom:  '$2',
          paddingLeft:  '$3',
          paddingRight:  '$3',
```

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/preview.tsx
> +      <Text css={{ fontSize: '20px' }}>Web Preview</Text>
```suggestion
      <Text css={{ fontSize: '$large' }}>Web Preview</Text>
```

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/preview.tsx
> +        marginBottom: '40px',
```suggestion
        borderRadius: '$medium',
        marginBottom: '$7',
```

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/preview.tsx
> +          borderRadius: '4px',
```suggestion
          borderRadius: '$small',
```

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/preview.tsx
> +        <Text css={{ fontSize: '16px', color: isConnected ? '$successFg' : '$dangerFg' }}>
```suggestion
        <Text css={{ fontSize: '$base', color: isConnected ? '$successFg' : '$dangerFg' }}>
```

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/preview.tsx
> +      justifyContent: 'center', alignItems: 'center', padding: '40px', backgroundColor: '$bgSubtle', height: '100vh',
```suggestion
      justifyContent: 'center', alignItems: 'center', padding: '$7', backgroundColor: '$bgSubtle', height: '100vh',
```

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/preview.tsx
> +          {/* <span /> */}
```suggestion
```

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/startup.tsx
> +export default async () => {
is there a reason for doing a default export? i think we want to avoid doing default exports

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/startup.tsx
> +          {/* {params ? <AppContainer {...params} /> : null} */}
```suggestion
```

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/index.tsx
> +// AsyncMessageChannel.ReactInstance.handle(AsyncMessageTypes.STARTUP, asyncHandlers.startup);
```suggestion
```

2024-05-17 18:47 UTC, six7 commented on developer-knowledgebase/async-message-channel.md
> +              |      Figma Plugin Controller       |
want to turn this into a mermaid diagram?

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/AsyncMessageChannel.ts
> +  private startWebSocketConnection() {
lots of these functions feel like we should move them to either a shared websocket file or their own files alltogether in order to improve maintainabiltiy

2024-05-17 18:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/AsyncMessageChannel.ts
> +    switch (this.environment) {
any way where we can make this function overall more readable? lots of nested ifs and switch statements 🤔

2024-07-16 17:30 UTC, cuserox approved these changes
NIIICE!

General questions for my understanding, and a couple of code simplification suggestions. Let me know what you think!

I haven't played around much with it in the browser, will add any comments if there's breakages.

2024-07-16 17:30 UTC, cuserox commented on packages/tokens-studio-for-figma/src/AsyncMessageChannelPreview.ts
> +export class AsyncMessageChannelPreview {
This class is _almost_ the same as `AsyncMessageChannel`. Could we have a `Base...` class, then extend to either `AsyncMessageChannel` or `AsyncMessageChannelPreview`?

Again, saves some code duplication. If possible?

2024-07-16 17:30 UTC, cuserox commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/preview.tsx
> +      <Stack css={{ flex: 1 }}><span /></Stack>
Why not remove the `<span />` and wrap the `<Text>` in a container, and the actions / badge in another container? Then `justify-content: space-between`

2024-07-16 17:30 UTC, cuserox commented on packages/tokens-studio-for-figma/src/app/asyncMessageHandlers/startup.tsx
> +  const state = rootStore.getState();
Could this not be:
```suggestion
  const state = store.getState();
```

?

2024-07-16 17:30 UTC, cuserox commented on packages/tokens-studio-for-figma/src/app/components/Initiator.tsx
> +    console.error('not a valid message', err);
I saw this somewhere else in the PR, is `console.error(...)` maybe too harsh?

Also, what does `return null` do when it comes to user experience?

2024-07-16 17:30 UTC, cuserox commented on packages/tokens-studio-for-figma/src/asyncMessageChannel.test.ts
> +    const runAfter: ((() => void) | null)[] = [];
Could save `() => void) | null` as a type and avoid having to update it everywhere if it changes!

2024-07-16 17:30 UTC, cuserox commented on packages/tokens-studio-for-figma/webpack.config.js
> +  if (!measureSpeed) { // Set to true to enable SpeedMeasurePlugin (breaks Figma UI build)
Could this comment be more thorough?

If not here, perhaps in a doc section to go through the why's and how's 😄

2024-07-16 17:30 UTC, cuserox commented on developer-knowledgebase/async-message-channel.md
> +-
Accidental bullet point

2024-07-16 17:30 UTC, cuserox commented on developer-knowledgebase/async-message-channel.md
> +```
Great diagram!!! 🎉

2024-07-16 17:30 UTC, cuserox commented on developer-knowledgebase/async-message-channel.md
> +- `ReactInstance` - used from inside of `ui` entrypoint
Worth mentioning what `inFigmaSandbox` means?

2024-07-26 18:06 UTC, merged