2778 20 make sure rename token group and duplicate token group cannot share name with an existing token group
tokens-studio/figma-plugin pull request #2785
Opened 2024-05-22 11:51 UTC by robinhoodie0823

### Why does this PR exist?
Current plugin allows users to rename or duplicate token groups even there is existing token group with the name that user wants to update.

Closes #2778  

### What does this pull request do?
Added a condition variable to check whether it can rename or duplicate the token group with user input data.

### Testing this change

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/886e5b73-7841-4832-9716-34d850c0f068

2024-05-23 06:40 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx
> +        return tokenList.some((token) => token.name.split('.').includes(newName));
this would fail now if i had a token name like `foo.bar.something` and i tried to rename another group to `bar`. 

check the logic for single tokens - should be something similar to `startsWith` instead.

2024-05-23 06:42 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.tsx
> +    const isDuplicated = tokens[activeTokenSet].some((token) => token.name.split('.').includes(newName));
same comment with .includes - startsWith likely but check how its done for single tokens

2024-05-23 07:04 UTC, robinhoodie0823 commented on packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx
> +      if (selectedTokenSets.includes(tokenSetKey)) {
The function duplicates tokens to `selectedTokenSets`. There is a dropdown menu which user can select token sets where the token group can be duplicated to.

2024-05-23 18:08 UTC, six7 requested changes
thanks for the updates! I'd still like to see a test added for this 🙏

2024-05-23 18:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx
> +        return tokenList.some((token) => token.name.startsWith(`${newName}.`));
i think this also needs to include logic so that a group cannot share the name with a token

2024-05-23 18:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.tsx
> +    const isDuplicated = tokens[activeTokenSet].some((token) => token.name.startsWith(`${newName}.`));
same here, should make sure it cannot share name with a token

2024-05-23 18:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json
> +  "renameGroupError": "There is already exist token group with the name input",
```suggestion
  "renameGroupError": "There's an existing token or group with that name",
```

2024-05-23 18:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json
> +  "duplicateGroupError": "There is already exist token group with the name input",
```suggestion
  "duplicateGroupError": "There's an existing token or group with that name",
```

2024-05-25 08:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.test.tsx
> +  it('should not allow duplication when there are no duplicates', () => {
```suggestion
  it('should disable duplication when there are duplicates', () => {
```

2024-05-25 08:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.test.tsx
> +  it('should allow duplication when there are duplicates', () => {
```suggestion
  it('should not disable duplication when there are no duplicates', () => {
```

2024-05-25 08:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.test.tsx
> +  it('should not allow renaming when there are no duplicates', () => {
```suggestion
  it('should disable renaming when there are duplicates', () => {
```

2024-05-25 08:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.test.tsx
> +  it('should allow renaming when there are duplicates', () => {
```suggestion
  it('should not disable renaming when there are no duplicates', () => {
```

2024-05-25 08:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json
> +  "renameGroupError": "There's an exist token or group with that name",
```suggestion
  "renameGroupError": "There's an existing token or group with that name",
```

2024-05-25 08:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json
> +  "duplicateGroupError": "There's an exist token or group with that name",
```suggestion
  "duplicateGroupError": "There's an existing token or group with that name",
```

2024-05-25 08:08 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.tsx
> +        {!canRename && <ErrorMessage css={{ width: '100%' }}> {t('renameGroupError')} </ErrorMessage>}
```suggestion
        {!canRename && <ErrorMessage css={{ width: '100%' }}>{t('renameGroupError')}</ErrorMessage>}
```

2024-05-25 08:09 UTC, six7 approved these changes

2024-05-26 08:04 UTC, merged