2804 20 gradients that have references to variables inside fail to applycreate
tokens-studio/figma-plugin pull request #2815
Opened 2024-06-05 07:58 UTC by robinhoodie0823

### Why does this PR exist?
Current plugin dose not apply gradient token which have reference tokens.

Closes #2804  

### What does this pull request do?
Updated the value of gradient token when passing to function to apply token on node.

### Testing this change

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/c9bd2652-127f-4cf0-bcf0-052d214660ed

2024-06-06 13:42 UTC, cuserox requested changes

2024-06-06 13:42 UTC, cuserox commented on packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts
> -    const resolvedValue = defaultTokenValueRetriever.get(token)?.rawValue || givenValue;
👀 This error is also happening with **gradients that don't reference variables**.

📝 🔨 For example: I have `my-gradient: linear-gradient(#e66465, #9198e5)` and see another error like so:
```
...in set_fills: Expected "fills.[0].gradientTransform.0.0" to have type number but got NaN instead...
```

When passed to [convertStringToFigmaGradient](https://github.com/tokens-studio/figma-plugin/blob/2804-20-gradients-that-have-references-to-variables-inside-fail-to-applycreate/packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts#L35), with the value `linear-gradient(#e66465, #9198e5)`, it returns the following object:
```
gradientStops: { color: { a: 1, b: 0.8980392156862745, g: 0.596078431372549, r: 0.5686274509803921 }, position: NaN, ... },
gradientTransform: {  [NaN, NaN, NaN], [NaN, NaN, NaN] }
```
This `NaN` comes from the fact my `linear-gradient(#e66465, #9198e5)` doesn't have degrees, therefore [trying to convert it to degrees with **convertDegreeToNumber**](https://github.com/tokens-studio/figma-plugin/blob/2804-20-gradients-that-have-references-to-variables-inside-fail-to-applycreate/packages/tokens-studio-for-figma/src/plugin/figmaTransforms/gradients.ts#L21-L29) returns `NaN`, because we only have hex numbers.

Similarly, if I use `linear-gradient(0.25turn, #e66465, #9198e5)` or `linear-gradient(to top, #e66465, #9198e5)`, it will also fail ❌ 

🥁 Buuuut using `linear-gradient(45deg, #e66465, #9198e5)` - it still doesn't work 🤔 This is because we still get: `position: NaN` (all other values are now numbers)

✅ Finally, using this as a gradient works: `linear-gradient(45deg, #e66465 0%, #9198e5 100%)`

2024-06-06 13:42 UTC, cuserox commented on packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts
> -    const resolvedValue = defaultTokenValueRetriever.get(token)?.rawValue || givenValue;
Therefore, I believe the full fix for this would be to ensure that the [convertStringToFigmaGradient](https://github.com/tokens-studio/figma-plugin/blob/2804-20-gradients-that-have-references-to-variables-inside-fail-to-applycreate/packages/tokens-studio-for-figma/src/plugin/figmaTransforms/gradients.ts#L20) method has the correct fallbacks for when the string manipulation takes place, to avoid `NaN` results:
* If no angle degrees are given, default to `180deg` (not sure if that's the default?)
* If `to top` is given, translate to `0deg`
 
Anything else that could break it?! Suggestion 😇 Let me know if it makes sense and if you can reproduce my example.

2024-06-06 18:45 UTC, robinhoodie0823 commented on packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts
> -    const resolvedValue = defaultTokenValueRetriever.get(token)?.rawValue || givenValue;
@six7 I think we need to investigate `convertStringToFigmaGradient` function to handle several kinds of linear gradients.

"gradient": {
    "value": "linear-gradient(212deg, {root} 0%, {dark} 100%)",
    "type": "color"
  },
  "gradient1": {
    "value": "linear-gradient(212deg, #000000 0%, #ffffff 100%)",
    "type": "color"
  },
  "gradient2": {
    "value": "linear-gradient(#000000, #ffffff)",
    "type": "color"
  },
  "gradient3": {
    "value": "linear-gradient(#ffffff)",
    "type": "color"
  },

Only `gradient` works fine.

2024-06-10 07:38 UTC, six7 approved these changes

2024-06-10 07:38 UTC, merged