Fix/max width on instances
tokens-studio/figma-plugin pull request #2842
Opened 2024-06-11 10:13 UTC by LukeFinch

### Why does this PR exist?

Closes #2426 

### What does this pull request do?

Changes the logic to apply min and max-width on instances

### Testing this change

Create a component with autolayout
Create an instance of the component
Apply min/max width/height sizing through the plugin

### Additional Notes (if any)

2024-06-11 11:23 UTC, robinhoodie0823 approved these changes

2024-06-12 08:07 UTC, six7 requested changes

2024-06-12 08:07 UTC, six7 commented on packages/tokens-studio-for-figma/src/plugin/applySizingValuesOnNode.ts
> -    && !isPartOfInstance(node.id)
I think this part here needs to stay in - we cant apply min max width tokens on instance children, this would throw an error

<img width="563" alt="CleanShot 2024-06-12 at 10 07 18@2x" src="https://github.com/tokens-studio/figma-plugin/assets/4548309/a2882013-1bc7-4621-89ac-c34927bc2156">

2024-06-14 15:42 UTC, cuserox commented on packages/tokens-studio-for-figma/src/plugin/applySizingValuesOnNode.ts
> -    && !isPartOfInstance(node.id)
If this stays, then this is not the fully fledged fix? Can't see any other changes 😅

2024-06-15 09:12 UTC, six7 commented on packages/tokens-studio-for-figma/src/plugin/applySizingValuesOnNode.ts
> -    && !isPartOfInstance(node.id)
It basically just resolves the case descrbied in the issue: if the layer itself is an instance, we want to allow setting sizing related tokens (as this is possibly). However, if its *part of an instance* this wouldnt work because figma doesnt allow it.

2024-06-15 09:12 UTC, six7 approved these changes

2024-06-15 09:12 UTC, merged