2774 spike gradients driven by variables
tokens-studio/figma-plugin pull request #2884
Opened 2024-06-19 14:46 UTC by robinhoodie0823

### Why does this PR exist?
Current plugin can not assign color variables to gradient's color stops due to previous figma plugin does not support it.

Closes #2774 

### What does this pull request do?
Updated figma plugin has `boundVariables` field with `color` field to support color variable assigning to gradient's color stops.
Updated `gradientStops` with color variables Ids in it.

### Testing this change

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/35b8d03e-482b-48aa-981d-90dc40667e25

2024-06-19 14:54 UTC, macintoshhelper commented on packages/tokens-studio-for-figma/package.json
> -    "0x": "^5.6.0",
`0x` seems to be removed? It is used in a benchmark script

2024-06-19 15:03 UTC, robinhoodie0823 commented on packages/tokens-studio-for-figma/package.json
> -    "0x": "^5.6.0",
Added

2024-06-20 06:37 UTC, six7 requested changes

2024-06-20 06:37 UTC, six7 commented on packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts
> +const getReferenceTokensFromGradient = (rawValue: string): string[] => {
can you extract this into its own file and write a test? this should be able to properly extract values like

linear-gradient(90deg, {accent.bg} 0%, {accent.default} 100%) = [accent.bg, accent.default]
linear-gradient(90deg, {accent.bg} 0%, {accent.default} 50%, #ff0000 100%) = [accent.bg, accent.default]
linear-gradient({accent.bg} 0%, {accent.default} 100%) = [accent.bg, accent.default]

2024-06-20 06:37 UTC, six7 commented on packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts
> +const getReferenceTokensFromGradient = (rawValue: string): string[] => {
because this fails today:

![image](https://github.com/tokens-studio/figma-plugin/assets/4548309/41cf634f-81e7-4684-8f5d-a4d0880796c5)

2024-06-20 11:38 UTC, six7 approved these changes
🎉

2024-06-20 11:38 UTC, merged