2.0: Fix order of keys when pushed to remote
tokens-studio/figma-plugin pull request #2914
Opened 2024-06-24 06:41 UTC by six7

Closes #2907

With 2.0 we seem to have introduced a regression when it comes to the order of token keys. We made it so that `type` always comes first, then `value`, and so on. This is bad because we need to respect users key ordering.

With this PR we're now respecting the order and keeping it the same by not destructuring the object.

### Before

<img width="692" alt="CleanShot 2024-06-24 at 08 39 54@2x" src="https://github.com/tokens-studio/figma-plugin/assets/4548309/cf8b56df-bb2f-49d2-b2f7-81877413dda8">

As you can see in this screenshot we reordered keys, even though the user didnt specify that.

### After

<img width="710" alt="CleanShot 2024-06-24 at 08 40 55@2x" src="https://github.com/tokens-studio/figma-plugin/assets/4548309/e407ea8c-148f-44a1-be54-da11eca1d12e">

Here's me after the change just adding a modifier - note how it preserves the order of `value` first.

2024-06-25 10:09 UTC, akshay-gupta7 requested changes

2024-06-25 10:09 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/utils/convertTokensToObject.ts
> +        tokenWithoutName[TokenFormat.tokenValueKey] = tokenWithoutName.value;
would it be better to move these two lines outside the if-else considering they are being set in both the conditions

2024-06-25 13:56 UTC, cuserox commented on packages/tokens-studio-for-figma/src/utils/convertTokensToObject.ts
> +        delete tokenWithoutName.inheritTypeLevel; // Remove it to avoid altering the order
Could this `delete` be replaced by a `filter` / `reduce` (or something that doesn't mutate the original object) as it's already looping through it?

2024-06-26 07:44 UTC, six7 commented on packages/tokens-studio-for-figma/src/utils/convertTokensToObject.ts
> +        delete tokenWithoutName.inheritTypeLevel; // Remove it to avoid altering the order
fixed in 92732eff8c016a59ce17a89d14eb085e3abcc1c8

Overall: We should be able to get rid of this file - i checked an much of this logic is repeated in stringifyTokens which already does this - I'll add to DX as things to simplify

2024-06-26 07:45 UTC, six7 commented on packages/tokens-studio-for-figma/src/utils/convertTokensToObject.ts
> +        tokenWithoutName[TokenFormat.tokenValueKey] = tokenWithoutName.value;
In the state of the PR that you reviewed, yes! howver with 92732eff8c016a59ce17a89d14eb085e3abcc1c8 no more - as the logic now properly diverges

2024-06-26 08:01 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/utils/convertTokensToObject.ts
> +        tokenWithoutName[TokenFormat.tokenValueKey] = tokenWithoutName.value;
got it!

2024-06-26 08:01 UTC, akshay-gupta7 approved these changes

2024-06-28 06:29 UTC, merged