2904 20 creating styles no longer attaches it to themes
tokens-studio/figma-plugin pull request #2923
Opened 2024-06-26 10:58 UTC by robinhoodie0823

### Why does this PR exist?
Current plugin has problem in token resolving logic, so it merges same name tokens but with different internal parent.

Closes #2904  

### What does this pull request do?
Updated token resolving logic to check token's internal parent to prevent merging of same name tokens.

### Testing this change

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/41d34ed6-dc13-4833-a786-54e31048c931

2024-07-02 11:29 UTC, cuserox approved these changes
Looks like it works well. Tested locally 👌

2024-07-05 10:36 UTC, six7 requested changes
The PR has a flaw:

You selected "Prefix styles with active theme name", but the styles that were created are only prefixed for the `light` theme - the `dark` tokens are not prefixed at all?

<img width="214" alt="CleanShot 2024-07-05 at 12 29 25@2x" src="https://github.com/tokens-studio/figma-plugin/assets/4548309/bf80260e-ac01-4d29-b040-718ff34c300c">

In that case the expectation is that there's 2 groups of styles created:

`light/...`
`dark/...`

2024-07-08 06:47 UTC, six7 commented on packages/tokens-studio-for-figma/src/utils/TokenResolver.ts
> +    if (memoKey && this.memo.has(memoKey) && token.internal__Parent === this.memo.get(memoKey)?.internal__Parent) {
For me right now it's hard to understand why we do this and I'd like to understand.

2024-07-08 08:53 UTC, robinhoodie0823 commented on packages/tokens-studio-for-figma/src/utils/TokenResolver.ts
> +    if (memoKey && this.memo.has(memoKey) && token.internal__Parent === this.memo.get(memoKey)?.internal__Parent) {
Yes. The current token resolving logic does not check token's parent name, so it merges tokens with same name but in different token sets.

2024-07-11 08:13 UTC, six7 approved these changes

2024-07-11 09:30 UTC, merged