Sync provider form updates
tokens-studio/figma-plugin pull request #2948
Opened 2024-07-01 20:10 UTC by akshay-gupta7

Resolves #2871

2024-07-02 17:32 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/BitbucketForm.tsx
> +            rel="noreferrer"
Need to update this Bitbucket URL to latest doc

2024-07-02 17:33 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
> +        </Text>
Need to add the Tokens Studio links here as well

2024-07-04 11:03 UTC, cuserox requested changes
Missing translations and a couple of improvements, let me know if it makes sense!

2024-07-04 11:03 UTC, cuserox commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/GenericVersioned.tsx
>  export default function GenericVersionedForm({
This form seems like it has a slight grey tinted background instead of white?

<img src="https://github.com/tokens-studio/figma-plugin/assets/114073780/cc38f5ca-6344-488b-8ae9-1acba93161e5" width=300 />

2024-07-04 11:09 UTC, cuserox commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/BitbucketForm.tsx
> +            rel="noreferrer"
Not published yet? As it leads to a 404: https://docs.tokens.studio/sync/bitbucket

2024-07-04 11:23 UTC, cuserox commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
> +        </Text>
As the 2nd part says _"If you are already using the Studio platform and need help setting up the sync, read the Tokens Studio Sync guide here."_ either: update the text to say (coming soon maybe?) or just remove it?

Some users might get frustrated, but can discuss!

2024-07-06 10:05 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/BitbucketForm.tsx
> +            rel="noreferrer"
Will be done in https://github.com/tokens-studio/plugin-docs/pull/261

URL is going to be `https://docs.tokens.studio/sync/bitbucket`

2024-07-06 10:09 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/GenericVersioned.tsx
>  export default function GenericVersionedForm({
I think we can address this in a separate issue as I didn't change the colour of the form in this

2024-07-09 07:54 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/modals/CreateStorageItemModal.tsx
> +      bitbucket: 'BitBucket',
```suggestion
      bitbucket: 'Bitbucket',
```

2024-07-09 07:54 UTC, six7 commented on packages/tokens-studio-for-figma/src/i18n/lang/en/storage.json
> +  "gitHubExplained": "Connect your Github code repository with Tokens Studio for remote token storage with version control and two-way sync controlled within the plugin.",
```suggestion
  "gitHubExplained": "Connect your GitHub code repository with Tokens Studio for remote token storage with version control and two-way sync controlled within the plugin.",
```

2024-07-09 10:39 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/SupernovaForm.tsx
> +          <Link href="https://learn.supernova.io/" target="_blank" rel="noreferrer">
Yes, done!

2024-07-09 10:40 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/GitForm.tsx
> +            href={`https://docs.tokens.studio/sync/${values.provider}?ref=addprovider`}
most of the part of the link is static anyway and the dynamic part is already being passed in values.provider

2024-07-09 10:44 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
> +        </Text>
You can check out the latest designs here:
https://www.figma.com/design/k9jBhSPZj8zti5XoYOYXox/Tokens-Studio-for-Figma%3A-All-views?node-id=120-16115
We can discuss with Sam in case we need any updates

2024-07-09 12:39 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
> +            rel="noreferrer"
Added the signup link here

2024-07-09 12:44 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
> +            target="_blank"
sync guide URL in place:
https://docs.tokens.studio/sync/tokens-studio

2024-07-09 14:35 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/StorageItemForm/TokensStudioForm.tsx
> +            rel="noreferrer"
Added the signup link here

2024-07-10 17:19 UTC, cuserox approved these changes

2024-07-10 17:20 UTC, cuserox commented
Nice one 😄

2024-07-10 17:23 UTC, merged