2984 pull from GitHub indicator remains on when pull was successful
tokens-studio/figma-plugin pull request #2986
Opened 2024-07-10 16:24 UTC by robinhoodie0823

### Why does this PR exist?
Current plugin checks if there is updates on remote storage (like github) every 60 seconds. So even I pull tokens from github, their is pull token indicator on and it will be disappeared after another 60 seconds.

Closes #2984  

### What does this pull request do?
Updated logic to change `hasRemoteChange` variables just after pull tokens from remote storage.

### Testing this change

### Additional Notes (if any)

2024-07-11 07:52 UTC, six7 requested changes

2024-07-11 07:52 UTC, six7 commented on packages/tokens-studio-for-figma/src/app/components/Footer.tsx
> +      setHasRemoteChange(false);
i think we should rather fix the bug inside `pullTokens` directly instead of applying a band-aid.

something inside `pullTokens` causes the blue dot to set it to `hasRemoteChanges`: true.. instead of it seeing the changes as the same

2024-07-30 13:37 UTC, cuserox commented
When this PR gets merged (https://github.com/tokens-studio/figma-plugin/pull/3035) I'd say this should get re-tested. Calculating the difference between local and remote changes was causing lots of issues!

2024-08-07 06:25 UTC, six7 commented
Closing as #3048 fixes this

2024-08-07 06:25 UTC, closed without merging