2978 box shadows that reference a color token that is connected to a variable will have their spread as 0 always
tokens-studio/figma-plugin pull request #2990
Opened 2024-07-11 15:13 UTC by robinhoodie0823

### Why does this PR exist?
Current plugin resets `spread` property of shadow token if the shadow token has reference token and variable id of the reference token.

Closes #2978  

### What does this pull request do?
The root cause is the figma function `setBoundVariableForEffect` resets `spread` property. You can find out the discussion [here](https://forum.figma.com/t/setboundvariableforeffect-bug/59788).

### Testing this change

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/cd807adf-d76a-4bbd-989d-46ae61e32be0

2024-07-12 06:17 UTC, six7 requested changes
Except for logs good to merge!

2024-07-12 06:17 UTC, six7 commented on packages/tokens-studio-for-figma/src/plugin/setEffectValuesOnTarget.ts
> +    console.log('resolvedToken in setEffectValues: ', resolvedToken);
remove logs

2024-07-15 16:13 UTC, cuserox commented on packages/tokens-studio-for-figma/src/plugin/setEffectValuesOnTarget.ts
> +            boundVariables: updatedEffect.boundVariables
Nice fix! 👏  Would you mind placing the discussion link here, with a small explanation as to why it's needed?

In case Figma fix it in the future and we no longer need this override 😇

2024-07-15 16:14 UTC, cuserox approved these changes

2024-07-16 10:28 UTC, merged