Fix double scroll in themes
tokens-studio/figma-plugin pull request #3027
Opened 2024-07-24 20:32 UTC by akshay-gupta7

Resolves #3006

2024-07-30 14:30 UTC, macintoshhelper approved these changes
LGTM

2024-07-30 15:50 UTC, cuserox requested changes
Nice work!

A small change to make the event listener safer when scrolling. Ensure to test out the times it renders and gets called properly 😄

2024-07-30 15:50 UTC, cuserox commented on packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx
> +  }, []);
Let's debounce this method, otherwise there's a chance that it'll get called many times [onScroll](https://github.com/tokens-studio/figma-plugin/pull/3027/files#diff-db0a813a6d988b1b509760080dbdac0d52ba0ffd7cece9997f9337673f352c83R240) 🙃 

Untested, but would something like this work?
```
const handleThemeListScrollDebounced = debounce(updateThemeListScrollPosition, 300);
```

Need to import from `lodash.debounce` and perhaps play around with the delay so it's not too slow!

Some inspiration ✨ https://hackernoon.com/eliminating-event-storms-with-debouncing-in-javascript

2024-07-30 17:40 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx
> +  }, []);
Hey @cuserox, thanks for this suggestion, have implemented it! Do have a look!

2024-07-30 17:41 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx
> +
used 200ms for now

2024-08-05 08:56 UTC, cuserox approved these changes
Good to go, debouncing for the win 💯

2024-08-05 11:43 UTC, merged