Fix license key padding
tokens-studio/figma-plugin pull request #3043
Opened 2024-08-01 08:45 UTC by akshay-gupta7

Resolves #3038 

<img width="392" alt="Screenshot 2024-08-01 at 2 13 47 PM" src="https://github.com/user-attachments/assets/529a7c1e-aa26-4e6b-85b8-a2b1dce2489d">

2024-08-01 12:19 UTC, cuserox commented on packages/tokens-studio-for-figma/src/app/components/AddLicenseKey/AddLicenseKey.tsx
> +          {licenseKeyError && (
Can we "push things down" if possible? Therefore: `css={{ marginBottom: '$2' }}` on the input 🤝 

Or `css={{ paddingTop: '$2' }}` here.

Removes the potential of margins collapsing, which can happen when you have conflicting marginTop & marginBottom.

2024-08-01 12:19 UTC, cuserox requested changes
Small CSS tweak. Good to go after the change 🫰

2024-08-01 17:32 UTC, akshay-gupta7 commented on packages/tokens-studio-for-figma/src/app/components/AddLicenseKey/AddLicenseKey.tsx
> +          {licenseKeyError && (
Done!

2024-08-05 08:55 UTC, cuserox approved these changes
Thanks for making the change! 🥇

2024-08-05 11:42 UTC, merged