Disable cache for Bitbucket
tokens-studio/figma-plugin pull request #3200
Opened 2024-11-05 18:10 UTC by DimitarNestorov

### Why does this PR exist?

We're not able to fetch updates for 15 minutes due to Cache-Control header.
![image](https://github.com/user-attachments/assets/8d7733bd-d28c-491e-b13e-52494c4c7fb8)

### What does this pull request do?

Disables cache for Bitbucket requests

### Testing this change

Open plugin in Figma app and check if pulling is cached

2024-11-07 13:34 UTC, akshay-gupta7 requested changes
@DimitarNestorov thank you for submitting a PR.
There are failing tests though, can you take a look.
we can review once the tests pass

2024-11-10 20:26 UTC, six7 approved these changes
🙏  Thank you!

(note: The Tests are failing because of how our .env variables for tests are set up, PRs of non-maintainers are not getting those env variables, thus causing them to fail, something for us to fix).

2024-11-10 20:26 UTC, merged

2024-11-14 10:03 UTC, DimitarNestorov commented
Thanks for merging! @six7 @akshay-gupta7 do you have any ideas when a new version of the plugin will be released?

2024-11-17 18:32 UTC, akshay-gupta7 commented
> Thanks for merging! @six7 @akshay-gupta7 do you have any ideas when a new version of the plugin will be released?

@DimitarNestorov , we haven't finalized the date yet, should be coming soon within the weeks ahead. Shall keep you posted with any developments on the date we choose